#!/usr/bin/perl

perl -pe 's/gz\n/gz\t/g' NumSeqs.trim #| awk 'NR == 1 { max=$2; min=$1; sum=0 } { if ($2>max) max=$2; if ($2<min) min=$2; sum+=$2;} END {printf "Min: %d\tMax: %d\tAverage: %f\n", min, max, sum/NR}'
