>Chl|comp11464_c15_seq1_380-931
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------LFTGNTALCFTAWLEGKVKFGQVLKNWICAYSGNIL------------
--------------------------------------------GCALMLAIFTNTGLL-
PQLS--KGAEAMALYKTAAPFKETFLKAICAN-WFVCLAVWQCLGANSFGGKFIACL---
-----GPVSAFV-------------------CIGLEHCIANLFFVPLGIFVGA-N---VT
FQQFLT------------------------------------------------------
------------TN----------------------------------------------
-------------------------------------------------LIPV--TLGNI
VA-------------------GTVCMATVYSLLYGALGRKI-------------------
------------------------------------------------------------
------------------------------------------------------------
------------------TGEAKTA---
>Clo|comp48751_c0_seq1_2-1102
--------------------ANSFNQHITMLQLQTSRAGLKPLRQGLCPKTAAAVRPRTV
TIVAVGRPAGGGSRMPL---------------------------GGSGASPERTTKSEGN
GAPAPAPAPAA-------------------------------------------------
------------------------AAPTGPQAVTLTGPAPIQAVLAPAQIYEAISNLGAA
KAAAPFWKTMLLGVVAGCYVALGAALLLTVGPNCM------GIAAQNPGLAKYITGAI--
---------------------------------------------------------GFP
YALLAILVCGSELFTGNTAVLTTAVYEGKATLKQLAKSWSASYLGNII------------
--------------------------------------------GCAIGVAMLLNCGLL-
PLFQ--NGIAAISVPKVSYPLSQVFVKAIMAN-WFVCLAVWQCTAAQTMGGKFIACL---
-----GPVSAFV-------------------CIGLEHCIANLVFVPLGILTGVPG---VT
WEAFIF------------------------------------------------------
------------KN----------------------------------------------
-------------------------------------------------LIPV--TIGNI
VA-------------------GTLCVATVYAFCYGKPGKKL-------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------GA
>Chl|comp6145_c0_seq1_3-1163
-----------------------------------------------SSGSSGRPLRRAH
LWCAAAYEPGLNGAGPTTTGPAPRQRSHELTVSSSGDPLPVSLSGAGGAAVAAAIEGAAK
SGAAPNIVINV-------------------------------------------------
-----------------------YAADPSAAVALPGDAVPVKAVLAPPDVYAACAKMGAY
KAQQPAWKNLMLAVAAGCYTAMFGALLLMVGPNCG------GLAASNPGLARYITGAI--
---------------------------------------------------------GLP
FQLMVIMVCGAELFTGSTAMVTAAYYEGKVSLCQLARQWAGSYAGNAL------------
--------------------------------------------GCALGVALLLGSGVV-
KGLM--PGVTAVSLAKISYPLHQTFIKAVLAN-WFVCLAVWQATAAQTAGGKFISIL---
-----GPLSAFI-------------------AIGFEHCIANMVFIPLGILTGVPG---VT
WDAFLF------------------------------------------------------
------------KN----------------------------------------------
-------------------------------------------------LIPV--TLGNI
FA-------------------GAVCVATLYSLAYGKLGKRV-------------------
------------------------------------------------------------
------------------------------------------------------------
-------QRALDLAELLRLRRAGLRDSR
>Pan|comp22338_c0_seq1_834-1970
---------------------------DYLSKVRAGVLTLYFLNEGCAPTKMQSAMSATR
CSFAVRPMPVRFTRVPIRVLAAAQVVTVT----SNGNG---NGNGYASTTTTTTPASAAV
YTSAPAPVPAT-------------------------------------------------
------------------------ATAPMPASVSVTTPVRTVSVLAPPQAYENATSVGAA
KAALPAMATFVQGIQAGAYIAFGAFLACSVGGSIP------GVAAANPGLAKLIFALI--
----------------------------------------------------------FP
VGLALVTNCGAELYTGNTMMLTCAVIEKKATMGQLAKNWSMSYLGNFV------------
--------------------------------------------GSIMMVFAVVATGLM-
A-TN--SMPAYIATAKTSLTFTEVMSRSILCN-WLVCCAVFSASAATSIPGRLMGLW---
-----PPIAAFV-------------------AIGLEHSVANMFMIPLGIMLGA-K---VT
WGEFLL------------------------------------------------------
------------NN----------------------------------------------
-------------------------------------------------LLPV--TIGNT
IA-------------------GVVLMAVAYSMSFGALGAKK-------------------
------------------------------------------------------------
------------------------------------------------------------
------------------PASA------
>Pan|comp46762_c12_seq10_3-707
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------KAFALAVLAGVYISFAALLSFSLLNAMP------GLLASNPGLAKLLSCSV--
----------------------------------------------------------FP
MGLALIVICGAELFTGNTALTTVAVLEGQATWSDVLARWAVVYAGNLA------------
--------------------------------------------GSLFMVAAVAATGLM-
A-GN--TVVPAVAVAKTSQPLLQVLMRAVLCN-WLVCLAVWTALAASTLPGKLLGLW---
-----LPVVAFV-------------------SLGLEHAVANMFIIPMGMALGA-P---VT
VAAFLT------------------------------------------------------
------------AN----------------------------------------------
-------------------------------------------------LLPV--TLGNI
FA-------------------GTVCTAGMYSLCYGRLGAGL-------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------
>Pan|comp46762_c12_seq13_3-707
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------KAFALAVLAGVYISFAALLSFSLLNAMP------GLLASNPGLAKLLSCSV--
----------------------------------------------------------FP
MGLALIVICGAELFTGNTALTTVAVLEGQATWSDVLARWAVVYAGNLA------------
--------------------------------------------GSLFMVAAVAATGLM-
A-GN--TVVPAVAVAKTSQPLLQVLMRAVLCN-WLVCLAVWTALAASTLPGKLLGLW---
-----LPVVAFV-------------------SLGLEHAVANMFIIPMGMALGA-P---VT
VAAFLT------------------------------------------------------
------------AN----------------------------------------------
-------------------------------------------------LLPV--TLGNI
FA-------------------GTVCTAGMYSLCYGRLGAGL-------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------
>Pan|comp46762_c12_seq16_143-706
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
MGLALIVICGAELFTGNTALTTVAVLEGQATWSDVLARWAVVYAGNLA------------
--------------------------------------------GSLFMVAAVAATGLM-
A-GN--TVVPAVAVAKTSQPLLQVLMRAVLCN-WLVCLAVWTALAASTLPGKLLGLW---
-----LPVVAFV-------------------SLGLEHAVANMFIIPMGMALGA-P---VT
VAAFLT------------------------------------------------------
------------AN----------------------------------------------
-------------------------------------------------LLPV--TLGNI
FA-------------------GTVCTAGMYSLCYGRLGAGL-------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------
>Pan|comp46762_c12_seq17_143-706
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
MGLALIVICGAELFTGNTALTTVAVLEGQATWSDVLARWAVVYAGNLA------------
--------------------------------------------GSLFMVAAVAATGLM-
A-GN--TVVPAVAVAKTSQPLLQVLMRAVLCN-WLVCLAVWTALAASTLPGKLLGLW---
-----LPVVAFV-------------------SLGLEHAVANMFIIPMGMALGA-P---VT
VAAFLT------------------------------------------------------
------------AN----------------------------------------------
-------------------------------------------------LLPV--TLGNI
FA-------------------GTVCTAGMYSLCYGRLGAGL-------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------
>tr|A8J4Q0|A8J4Q0_CHLRE.High.affinity.nitrite.transporter.OS=Chlamydomonas.reinhardtii.GN=NAR1.1.PE=4.SV=1
------------------------------------MKMQQLCPSPKMNCPRHARLAVAR
VQRVQQRTGIAILSRSVVANAAAGIASVS----QNGGS---NGNGAHATLTPVTPIAAP-
--AAPAPAPAA-------------------------------------------------
---------------------------------------PAPGVLPPAAAFNAIVAAGAA
KAAMPAWKTFLMGIMAGCYISFGGFMAVTAATMCA------GLGATNPILTRLVMGAL--
----------------------------------------------------------FP
FGLLITLVCGAELYTGNTALVTAAVAEGKATPKDLAKNWFWSYAGNAV------------
--------------------------------------------GSLLMVGLVAATGLL-
A-TS--PVAANMAVAKSALPFGQALVRGLLCN-WLVCSAVWMAAAATSLPGKALAAY---
-----LPVMAFI-------------------TLGLEHSVANMFFCSLGIVQGA-P---VS
WGAFLT------------------------------------------------------
------------NN----------------------------------------------
-------------------------------------------------LLPV--TLGNT
LA-------------------GVLCMAAAYCACFGAAGNKP-------------------
------------------------------------------------------------
------------------------------------------------------------
------------------AATAAPAAAK
>Sel|comp11872_c2_seq1_856-1686
------------------------------------------------------------
------------------------------------------------------------
----PPPPPAA-------------------------------------------------
----------------------------------INIPDPIPGVLPPAAVYAKVVDGGAG
KAALPWQKVLVLGIMAGVYIGFGALLSQVVGGNCP------GLAAANPGMQKMLVGAI--
---------------------------------------------------------GLP
VGLMLVLICGGELFTGNTAFVTAAALEGRASPRQLAKSWACSYIGNAI------------
--------------------------------------------GTALFISAICASGLM-
A-TA--TAPPAAAVAKTSLAFGTAFVRGVLCN-MFVCLGIWQATAATSLTGKFVGSW---
-----LPVSAFA-------------------AIGFEHSVANMFLVPMGIALGA-P---VA
LSTFLT------------------------------------------------------
------------AN----------------------------------------------
-------------------------------------------------LLPV--TLGNI
VG-------------------G-VLVALAYAYSFGSLGKPK-------------------
------------------------------------------------------------
------------------------------------------------------------
------------------TA--------
>Sce|comp18163_c0_seq1_727-1797
-----------------------------HLHLLPRCPRVAAITQGYTAATMQNLKARSS
APTLQRRAAAVPSVRRVPLLVRAQAVSLG----QTVTA---NGNGATTS-----------
------------------------------------------------------------
---------------------------AQPIQVDVNVPQPTPALLGPVEAYQYVAKDGAK
KAAMTPFKTFVMALYAGAYIAFGGFLGLTVCNGCP------ALVAANPGLAKLLFALV--
----------------------------------------------------------FP
VGLTMNTLHGTELFTGNTMKLPAAIYEGKTNMGGLIKNWFWSYSGNFI------------
--------------------------------------------GSLLFVAAVVASGVL-
AQGA--VYPIKTAMYKASLPWGQAFIRAIMAN-WLVCVAVWNAGSASSLPGKVLGIW---
-----PPIAAFV-------------------AIGLEHSVANMFLIPLGIALGA-D---LT
FSQFIF------------------------------------------------------
------------QN----------------------------------------------
-------------------------------------------------LIPV--TLGNI
VG-------------------GLVFMGTASSIFYGALGGAK-------------------
------------------------------------------------------------
------------------------------------------------------------
------------------KMSEAAAH--
>Tet|comp27552_c0_seq1_874-1875
----------------------------------------------MQTATFKGTGLRAQ
LSSAAPRKALPVQSRRVTVGIRCQAAYVGTETTTTSTS---NGNGNGYA-----------
---AAAPAPAP-------------------------------------------------
--------------------------------------VLAPECLSPPEAYMAQVKDGVK
KAETGVLKTVIKGFFAGCYIAYGGFLGLTVVNSCP------GLLSTNPGLAKLLFAAI--
----------------------------------------------------------FP
VGLYMTIMTGSDLFTGNTMKFPAAIIEKKASVGQLIKNWFWSYSGNFI------------
--------------------------------------------GSLFLVAMVAASGVL-
A-GS--TYPIKTAIAKSSLTWSQAFIRAVLAN-WLVCVAVWCAGSASSLPGRILGLW---
-----PPICAFV-------------------AIGLEHSVANMFLIPMGIALGA-N---IT
FSHFIT------------------------------------------------------
------------AN----------------------------------------------
-------------------------------------------------LIPV--TLGNI
VG-------------------GMLFMGLSNAYFFGSLGKAK-------------------
------------------------------------------------------------
------------------------------------------------------------
------------------TA--------
>Chl|comp13737_c0_seq1_542-1795
------------------------------------------------------------
------------------------------------------------------------
-MSSRPRTLQAHER----------------------------------------------
-------LFSRVLHGRLATEQDTKPDSFAAHVAAPAAPGAIQAISSPPENYAFHMEAAAQ
KNLYPFPKLVILGLLAGAYISMGYSLCSLVAGQLSK-----EFRLEQPGAFNFLFGIF--
---------------------------------------------------------GFP
MGLTLCVVAGADLFTSNCMYATIAVAEGRYGLLGLLRCWLVSYFSNLL------------
--------------------------------------------GSLLMVGLMMGGDVFY
GGRK--DFVIDLALAKVSHSFGVTLCKGILCN-WLVCLAVWQGNMARDLTGKFVGIF---
-----LPNSAFV-------------------SMGFEHCIANMYLVPLSMALGS-N---IS
VGTFIT------------------------------------------------------
------------KN----------------------------------------------
-------------------------------------------------LIPA--TIGNI
IG-------------------GAGFVGIAYALSFGSPGHAV-------------------
-----FDAWEHALAC----------------MPCAGRLAPQPALPSHAPLRHSDTLGFGA
HGAHAGGLQGGHANGLANGHFGKAPTMHRMPTG---------------------HLAPPS
PVAEEQDGSSFESGKTGSTNHNGVLRGS
>Clo|comp48958_c0_seq1_944-2176
------------------------------------------------------------
-----------------------------------------MRESTMDTFGSPAKEAPQM
KKRSEPPSLQA-------------------------------------------------
--------WHSVLYGRHKRQG-------VPHQAPIKTIAAAALIMTPDEVYDFNASTAKF
KHEYPLPKLIVLGILAGAYIGLGYSLCCLVGGMLSY-----DLRHEEPGLFNFLFSIF--
---------------------------------------------------------GFP
MGLTLCVVAGADLFTSNCMYVVIAMSEGRYGALGALRTLFVSYFCNLG------------
--------------------------------------------GALMLVGLMSSGMVF-
SNRA--EFVIELANKKVSYPWTAAFVKGILCN-WLVCLAVWQGNMARDLTGKFIGIF---
-----LPNSAFV-------------------AMGFEHSVANMFLIPLSMVLGS-D---IS
VGTFLT------------------------------------------------------
------------KN----------------------------------------------
-------------------------------------------------LIPV--TLGNI
VG-------------------GGFFVGAMYALALGTPGHAI-------------------
-----QDAWDHQVSK----------------LSC---------FKGEEEGEEGELGGFGA
PTA-ANGTASTRAGKFDLNGLEDGPRSSPAFSGGATFKQH--------------HLAPLS
EV------SSGNGALAGSGRH------F
>Cos|comp32559_c0_seq1_77-1228
----------------------------------------------------TNCH--SE
-----ESNPSWMGR-----------HSSHIMPQSNGSH---HLSPPHLDLESQTGHAPPK
DTSSEMAKSQQ-------------------------------------------------
------------CLLKISSSH---TDKHKE--------IPITVILTPPQILQHVADAGVA
KAKNPIFSELVLGILAGVYIGFGFSLCMLSAGQLSE-----ELRLEQPGLFNILFGIF--
---------------------------------------------------------GFP
FGLTLCVVAGASLFTSNVLYMTTAFWEGKVKWFHVIYVLVFSWFTNLI------------
--------------------------------------------GSLLLGGLMVWGQVF-
HDRE--GFTNHLAHKKTSYSFEVAFVKGILCN-WLVCLAVWQANAANDLMGKAIGVW---
-----LPISAFV-------------------AMGFEHCIANQFMLPLSMQLGS-D---VT
MDSLIV------------------------------------------------------
------------KN----------------------------------------------
-------------------------------------------------LIPV--TLGNF
VG-------------------GALFVGTFYCFAYGRMGKSV-------------------
-----NKRISSAWTW----------------MKR----KTTTCFVRKQAVKESGSGGNNP
HKDVADSLA---------------------------------------------------
----------------------------
>Cos|comp35068_c0_seq1_354-1541
--------------------------------------MSAPTNGYAAPSSTTNGHDASH
-----DDKPDWFAR-----------HSFPALPEST-SH---SKKFLGNDASHPSLH---H
DEATSAPTAAA-------------------------------------------------
------------IPGQSQDPN---SDHHHE--------VPATIYLTPPQILDHVADAGGA
KTKSPFFSELILGIMAGAYIGFGFSLCMLGAGQLSE-----ELRMTEPGLFNILFGVF--
---------------------------------------------------------GFP
FGLTLCVVAGASLFTSNVLYMTTALWQGKAKWYHVIYELVFSWFANLC------------
--------------------------------------------GSLLLAGLMVWGQIF-
HDRE--EFTLHLAHKKTGYPFQVAFVKGILCN-WLVCLATWQANGANDITGKAVAVW---
-----LPISAFV-------------------AMGFEHCIANQFMIPLSMMLGA-D---IT
FYQMIV------------------------------------------------------
------------CN----------------------------------------------
-------------------------------------------------WIPV--TLGNL
VG-------------------GGLFVATFYCMAYGRPGTAV-------------------
-----NKQVDKGWHW----------------SKE----KVASGMGRREPFNASTSKGRSS
SKDVLSSVP---------------------------------------------------
----------------------------
>Sce|comp19300_c0_seq1_275-1270
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------MKDFPEQQQADSHGHAQRMCLQPPEIYMYMADGGRD
KTQNSVLRESVLGILAGCFIGFGFSTCMLAAGQLSP-----EYRKAEPGMFNLLFGAY--
---------------------------------------------------------GFP
VGLSMCVINGASLFTSNIAYMAAACIQRKSSAGQGLFVLLLSYFMNLA------------
--------------------------------------------GSLLLVQFMVAGHVF-
VHRE--AFTIELALKKTSYSFGATLTKGILCN-WLVCMAVWQGNAAQDITGKLLGIW---
-----FPISAFV-------------------TMGFEHCVANMFVIPLAIKLGA-P---IS
VGTFIV------------------------------------------------------
------------KN----------------------------------------------
-------------------------------------------------LIPA--TLGNL
IG-------------------GAVFVASMYGLAYGDWEKAV-------------------
-----NSAGAAAWAC----------------LT--------------GRSRSSGSSSSLS
SRDSLSERADAYVAALPTTVSKAGQV----------------------------------
----------------------------
>Tet|comp30949_c0_seq1_1693-2961
--------------------------------------MSHPRASWDGERPTRQFRDSVV
-----EMNPGAGLRCIGDDLHEPAWHDCPAGPQAAMGA---PVR--------PFVHIKCM
SNQHLPPFGKP-------------------------------------------------
------------LGGSSHSSDSIPADHHAE--------MEVKAYLAPPEIYQHIADAGAA
KLKGSFVRELVLGILAGCYIGFGFSLCMLCAGQLSK-----DLRTREKGLFNFFFGAF--
---------------------------------------------------------GFP
FGLTMCVLNGSSLFTSNVAYMAAAFIEGKAPARGAVRIVAMSWATNFI------------
--------------------------------------------GALLLGQMMLWGQVY-
HDRE--DFTVELGHKKTSYSFGATLVKGILCN-WLVCMAVWQANAAQDIGGKVLGIF---
-----LPISAFV-------------------AMGFEHCVANMFMLPLSMRLGA-D---IN
VATLLL------------------------------------------------------
------------RN----------------------------------------------
-------------------------------------------------LIPS--TMGNV
IG-------------------GGFFVATSYGLAFGAGEKAV-------------------
-----VQAGKAASSA----------------LLR----AWPACL------RRAESHSLLP
THSSLPCTGAKA------------------------------------------------
--------TGNAPTTAAGASASAQLTQS
>Sce|comp78959_c0_seq1_1-729
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------VGGNAPK-----EWLEDSPGLFSLLFGAV--
---------------------------------------------------------GFP
FSFTIILVCGAELYTSMCAYMMAAWWERKVSMATCLRMWVLSWLWNFV------------
--------------------------------------------GCAIFVGLMYASNLY-
HHKD--WYIKLLAVKKVSNSWGVTLVQGIFAN-WLVCVATWQANAAQDLIGKAVAIW---
-----LPISAFA-------------------MLGFEHCIANQFLIPMGIALGA-P---VT
ARQFVA------------------------------------------------------
------------SN----------------------------------------------
-------------------------------------------------LIPA--TIGNW
IG-------------------GAICMATMYAWVYGSPPQQL-------------------
-----AAWWAQRQVG----------------GGV----QSDAVAVVTESNN---G-----
------------------------------------------------------------
----------------------------
>Sel|comp11989_c2_seq1_2-1300
---ANIREDRAQLAVRARRAGKGFARASPRGLPSVRAASGMAPPNFRQNGTVPATDEQSP
SMMTLITKKASGEAPPSVRLPMPGGDYAAAEPGSHTPR----------GGMGLRRRSERI
HGDHDDAEHKY-------------------------------------------------
------------PMPRFPPAHTSAAFEAVA--------VRKSLILTPAEVYAECAHHGEE
KAQFGWLKLLVLSVIAGCYVGFGFTICLMVGGNVGT-----DIYTDHPGLFSLVFGAV--
---------------------------------------------------------GFP
AAFTMIVVCGAELFTSMCAYATAAWWEGRLGMLSCIRLWVITWCGNFA------------
--------------------------------------------GCAIFIGLIYATDLY-
EGKD--WYTLLLAQKKVHHSFGSAFVRGIFAN-WLVGIATWQANAAQDMAGKAIAIW---
-----LPISAFA-------------------MLGFEHVIANQFLLPMAIALGA-P---LS
ARDVIV------------------------------------------------------
------------GN----------------------------------------------
-------------------------------------------------FIPA--TLGNW
VG-------------------GAVCVATTYAFAFGRPNKIV-------------------
-----TAWFAGLRMP----------------RGR----KAAAGGGAGAQRRKLGA-----
------------------------------------------------------------
----------------------------
>Sel|comp12474_c0_seq1_630-1046
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------MGRPLAGARTTRRRRQ
PSPSPFPPPALRRKASLKHPTPHTNHPKTPHQMGFEHCIANQFLLPMAVALGA-P---LS
ARDVIL------------------------------------------------------
------------GN----------------------------------------------
-------------------------------------------------LIPT--TLGNW
VG-------------------GAVFVGTVYAFAYGRPNALI-------------------
-----VAWWSERCTA----------------RRG----AGAAGLAGGLAGRV--------
------------------------------------------------------------
----------------------------
>Sel|comp12474_c0_seq13_630-1046
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------MGRPLAGARTTRRRRQ
PSPSPFPPPALRRKASLKHPTPHTNHPKTPHQMGFEHCIANQFLLPMAVALGA-P---LS
ARDVIL------------------------------------------------------
------------GN----------------------------------------------
-------------------------------------------------LIPT--TLGNW
VG-------------------GAVFVGTVYAFAYGRPNALI-------------------
-----VAWWSERCTA----------------RRG----AGAAGLAGGLAGRV--------
------------------------------------------------------------
----------------------------
>Sel|comp12474_c0_seq17_630-1172
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------MSCAAQDLVGKVVAIW---
-----LPISAFV-------------------MMGFEHCIANQFLLPMAVALGA-P---LS
ARDVILGGCGGVGSSGLYGLHGRARRANRCAARPVRCALLCRRALKSPSPSVDCPLAHGR
LPRPSPLPRRAAGN----------------------------------------------
-------------------------------------------------LIPT--TLGNW
VG-------------------GAVFVGTVYAFAYGRPNALI-------------------
-----VAWWSERCTA----------------RRG----AGAAGLAGGLAGRV--------
------------------------------------------------------------
----------------------------
>Sel|comp12474_c0_seq7_630-1268
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------TLLLAQKKTHHGFGSCFVLGLFCN-WLVCIATWMSCAAQDLVGKVVAIW---
-----LPISAFV-------------------MMGFEHCIANQFLLPMAVALGA-P---LS
ARDVILGGCGGVGSSGLYGLHGRARRANRCAARPVRCALLCRRALKSPSPSVDCPLAHGR
LPRPSPLPRRAAGN----------------------------------------------
-------------------------------------------------LIPT--TLGNW
VG-------------------GAVFVGTVYAFAYGRPNALI-------------------
-----VAWWSERCTA----------------RRG----AGAAGLAGGLAGRV--------
------------------------------------------------------------
----------------------------
>Sel|comp12474_c0_seq5_630-974
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------MSCAAQDLVGKVVAIW---
-----LPISAFV-------------------MMGFEHCIANQFLLPMAVALGA-P---LS
ARDVIL------------------------------------------------------
------------GN----------------------------------------------
-------------------------------------------------LIPT--TLGNW
VG-------------------GAVFVGTVYAFAYGRPNALI-------------------
-----VAWWSERCTA----------------RRG----AGAAGLAGGLAGRV--------
------------------------------------------------------------
----------------------------
>Sel|comp12474_c0_seq9_630-1070
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------TLLLAQKKTHHGFGSCFVLGLFCN-WLVCIATWMSCAAQDLVGKVVAIW---
-----LPISAFV-------------------MMGFEHCIANQFLLPMAVALGA-P---LS
ARDVIL------------------------------------------------------
------------GN----------------------------------------------
-------------------------------------------------LIPT--TLGNW
VG-------------------GAVFVGTVYAFAYGRPNALI-------------------
-----VAWWSERCTA----------------RRG----AGAAGLAGGLAGRV--------
------------------------------------------------------------
----------------------------
>tr|Q6IYG4|Q6IYG4_CHLRE.Formate.nitrite.transporter.OS=Chlamydomonas.reinhardtii.GN=NAR1.4.PE=2.SV=1
----------------------MTDGGNGNGNGNVVGEALGKLSPLFKGIGSPAVDVEVP
ADQAEPVDEAEVNGRVYHDEHFNHGVHYADEGTAPAPV---GRKVTFNAALSKNMDSERM
TATTKPVQLGA-------------------------------------------------
------------PMPKWPANHQSAAFEAVS--------IKHSYILSPPEIFAECAHHGEE
KYNYPWYKLWVLTIIAGCYVGFGYTTCLLVGGMLDQAPGVGSPEEENYGLYKLIFGAV--
---------------------------------------------------------GFP
FGFTTIIVCGADLFTSLCAYMTAAWWEGKVRWHAVLYMLAVSWTGNFI------------
--------------------------------------------GCAIMVGLMTAGEVY-
RHKT--TTLFNVTYGKLEYGWGAVFVKGIFAN-WLVGIATWMANAAQDLTGKAVGIW---
-----LPISAFA-------------------MLGFEHSIANMFLFLMAWAMGA-N---IT
AKQFIW------------------------------------------------------
------------DN----------------------------------------------
-------------------------------------------------LIPA--TLGNF
FG-------------------GGVCLGTVYAFAYGRTPKLM-------------------
-----GAWIDQKLKR----------------S----------------------------
------------------------------------------------------------
----------------------------
>Clo|comp23893_c0_seq1_1470-2519
------------------------------------------------------------
------------------------------SSETAQAV---LSWDRMAGGSETKAHDTRL
ELTASPAGAEV-------------------------------------------------
---------------------------PRAPAPPITTPTQVNSLLTPPQIYDSLVHSAAY
RYKANLPKLILLGIQAGIYVGLGVSTCAIAGGSMSL-----ELRTKEPGLFNFLYAIF--
---------------------------------------------------------GFP
MGLTLIIFTGTDLFTSSCMYAAVGVLEGVFGLYGALRMVIVPYFSNLV------------
--------------------------------------------GALLLLGLQTGSEVF-
HGKKAADFIIAVAMKKCHLDWGVCFVRGIMAN-FLVCLAVWLAAASRDLTGKFIGVF---
-----LPISAFV-------------------ALAYEHCIANMLTIPMAMVLGA-P---IT
TSEFIR------------------------------------------------------
------------HN----------------------------------------------
-------------------------------------------------LIPA--TIGNF
VG-------------------GAALVGLMYALIYGRSGTAF-------------------
-----FAWWDRMALK----------------ASQ----RVQVMMHGRRGAAQPDLHT---
------------------------------------------------------------
----------------------------
>Sel|comp12474_c0_seq11_3-767
------------------------------------------------------------
--------------------------------------------GGGGGDDGLQKRSGRF
HGDHEEPMTSY-------------------------------------------------
------------PVPRFPPGHTSAAFDAVV--------VRKSLILSPAETYAECAHHGEE
KAKHGWLKMLMLCFIAGCYVSIGFSLCLLVGGNLGL-----DIYKERPGLFSLVFGAV--
---------------------------------------------------------GFP
TGFTFIVVCGGELFTSLCAYMAAAWWEGRVSARTCLRVWVVSWLGNFLGGRAACIFGGAY
AKPPFRSSTGCLVSVGCLPCILRRVVLWRRAASRPPLPAAPPPAGTATCLGLLLAARSY-
ENKD--AFTLLLAQK---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------
>Sel|comp12474_c0_seq6_3-776
------------------------------------------------------------
--------------------------------------------GGGGGDDGLQKRSGRF
HGDHEEPMTSY-------------------------------------------------
------------PVPRFPPGHTSAAFDAVV--------VRKSLILSPAETYAECAHHGEE
KAKHGWLKMLMLCFIAGCYVSIGFSLCLLVGGNLGL-----DIYKERPGLFSLVFGAVGA
LIIGHRRMRRGTRRCRVRRAQPVERAAGARRPSRPSLASGRERAKAQAPLHPNPNRAGFP
TGFTFIVVCGGELFTSLCAYMAAAWWEGRVSARTCLRVWVVSWLGNFL------------
--------------------------------------------GTATCLGLLLAARSY-
ENKD--AFTLLLAQK---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------
>Sel|comp12474_c0_seq15_26-766
------------------------------------------------------------
--------------------------------------------GGGGGDDGLQKRSGRF
HGDHEEPMTSY-------------------------------------------------
------------PVPRFPPGHTSAAFDAVV--------VRKSLILSPAETYAECAHHGEE
KAKHGWLKMLMLCFIAGCYVSIGFSLCLLVGGNLGL-----DIYKERPGLFSLVFGAV--
---------------------------------------------------------GFP
TGFTFIVVCGGELFTSLCAYMAAAWWEGRVSARTCLRVWVVSWLGNFL------------
--------------------------------------------GGRAATALAP------
------------ALCWASSATGWCGARSVLAGCFFVCGAVRWSV----------------
-----LPCAGGA---------LQTPSRQNSFLRGPQHA----------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------PPPPNLGGV
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------
>Pan|comp49906_c0_seq1_1-1380
-MDTIRNGDSAHDTA---DGLSDMGTACRLVQDVEAGQVAPRSKVSETASAKAGLGERSQ
---RVSLPGNGASSTPVSAADLDPALRAVSNIAGAPRD---ADGASAARTSLKPWQSQGF
HGKQRGPPSAP-------------------------------------------------
-------------PSSRVFKQAPAHDAHQE--------TAAAVILSPKQTYDHIVAAGVA
KTHLTLAKQVTQGVLAGFYISFSFMLCMTVGGQIS------TIQHDYPGIYNFILGSV--
---------------------------------------------------------GFP
LGLTVIMVVGADLFTSSCMYMITAWIEGRVSSYYVIRNWIISWWCNLA------------
--------------------------------------------GCLIMAQLVVWAGLFE
GAKS--SFPLYLAHKKTSASFGATLVKGILCN-WLVNLATWMANSARDLTGKAVGVY---
-----LPVSAFV-------------------TLGTEHVIANQFELSLAKMLGS-G---MS
IHTMVV------------------------------------------------------
------------RN----------------------------------------------
-------------------------------------------------LIPA--TIGNI
IG-------------------GAFFVGTLYAGTYGTLYERMWLRTTQLYIWLVPKRARER
ISAGCAATYDRLFGW----------------IDWGAITAPPAALPTTADGGGA-------
------------------------------------------------------------
----------------------------
>tr|Q6IYG1|Q6IYG1_CHLRE.Formate.nitrite.transporter.OS=Chlamydomonas.reinhardtii.GN=NAR1.3.PE=2.SV=1
MTQTNSPNTMEKKESTANDGLCDLAVTSRFVSAHGQGHTQPAAHENGQGSAQQSNGNSSS
PAVGVAINLGEANSAPGTNPEVAHAHKADVEAPEMPNV---ARQSEKVLTWMPSSQGLCM
SSAPASAVRKQ-------------------------------------------------
-------------TQGTSFKNAPKAEEHKE--------CAAAIILTPKQTYDHIVATGVA
KTTLPLSKQVTQGVLAGFYISFSFMLCMTVGGQIP------TIQANYPGIYNFILGSV--
---------------------------------------------------------GFP
LGLTVIMVVGADLFTSSCMYMMTAWIEGRVATYYVLKNWFLSWWCNLA------------
--------------------------------------------GCLIMAQLVVWAELF-
HGKE--SFPIFLAHKKTSYPFGATVVKGIICN-WLVNLAVWMANSARDVTGKAVGVY---
-----LPVSAFV-------------------TLGTEHVIANQFELSLAKMLGS-G---MS
LHTIIR------------------------------------------------------
------------DN----------------------------------------------
-------------------------------------------------WVPA--TIGNI
IG-------------------GAFFVGTLYAGVYGTLYERMWLRCLQVYVWVLPRAVRER
IHAARTAVYEKLFGW----------------VDWDYITTAPADVIRETAGQDLNEDSPGP
HDHAAIAKAGVSSAGGNSDNAGALDRKTGASTGAASQRGGVSRAGTSGLGRGGPARAISS
MLVDAVRNPPMTPFEKQRTEAALGSDVV
>tr|A8HPB4|A8HPB4_CHLRE.Formate/nitrite.transporter.OS=Chlamydomonas.reinhardtii.GN=NAR1.6.PE=4.SV=1
------------------------------------------------------------
------------------------------------------------------------
------------MS----------------------------------------------
-------TSIVVDPARGHAEERAQIGGLTAATASKGDAALFRLFITPLEVWNKVVATGVA
KAKYSWPKKVLLSFLAGAYLSFGMAFAFLVGGQLK------NIKVDDPGLYNVILGFF--
---------------------------------------------------------GLP
FGLTMIILMGSDLYTSDVTFMLAAWCEGKTKMTAVVWNLVYCWFGNLC------------
--------------------------------------------GSLFMVQMYIWGDVF-
SGRE--AFEESVALKKTSPDFGVNFVRGMLCN-WLVNIATWQAMTAQDVTGKFVGVL---
-----IPVTIFV-------------------ASGFEHCIANQFGIPMGMRLGG-TAQYVT
TSEAIV------------------------------------------------------
------------KN----------------------------------------------
-------------------------------------------------YIPV--TLGNS
VA-------------------AMIFIVGFYFFSIGSGHDMV-------------------
-----VNSWNSGVTRYLPPMLAGWLQTGDVVAAEGGLQPLPGKFIGDISVHYGGVAGGGG
GTPSHRGISAALRALTSSMRGTHAPPPAAVVSAQPQAATGEGANGKSMV-----------
----------------------------
>Sel|comp12474_c0_seq12_1-1050
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------TLLLAQKKTHHGFGSCFVLGLFCN-WLVCIATWMSCAAQDLVGKVVAIW---
-----LPISAFV-------------------MMGFEHCIANQFLLPMAVALGA-P---LS
ARDVIH------------------------------------------------------
------------ARQLGGRRRLCRHRLRVCLRPPKRSHRGVVERAMHGSPRRRRCRPGRR
PGRPRVSKGRCCRCAGGAAAGGGDGTRIWRRGVARLNPEPFIKQPFRPPVVPAQDTLAAC
AGSRRAQTPDPTAPKYPLPSCGYFSINGLYRWSPLHLCPLA-------------------
---------------------------------FNRERRPASHPHPRTTPQHPPTPQHQD
PPSPAATPAPSLQAYVACKGRGHVRSDQASTDAALRSAPHMQGGGNAATHPPTPRWCALF
ATLLPLRGLRHGPMRPAKSACNNTARQK
>Sel|comp12474_c0_seq8_1-954
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------MSCAAQDLVGKVVAIW---
-----LPISAFV-------------------MMGFEHCIANQFLLPMAVALGA-P---LS
ARDVIH------------------------------------------------------
------------ARQLGGRRRLCRHRLRVCLRPPKRSHRGVVERAMHGSPRRRRCRPGRR
PGRPRVSKGRCCRCAGGAAAGGGDGTRIWRRGVARLNPEPFIKQPFRPPVVPAQDTLAAC
AGSRRAQTPDPTAPKYPLPSCGYFSINGLYRWSPLHLCPLA-------------------
---------------------------------FNRERRPASHPHPRTTPQHPPTPQHQD
PPSPAATPAPSLQAYVACKGRGHVRSDQASTDAALRSAPHMQGGGNAATHPPTPRWCALF
ATLLPLRGLRHGPMRPAKSACNNTARQK
>Tet|comp324964_c0_seq1_2-346
------------------------------------------------------------
---------------------------------GTPTP---TSPARLTRRLTSLKERTHA
DNEDNDGVSDF-------------------------------------------------
------------PMPKWPVNHVSGAFESVA--------VKKSLVLSPPEIYAEIAHHGEE
KAKFHWFKLLLLTIVAGCYVGFGFTLCMIVGGNLPK-----S------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------WL-------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------
>Chl|comp11464_c17_seq2_2-649
-----------------------------------PRSRCCPIACNPPRIGRSIAASRTA
ASSMQAAQIRGCGALPMRASVRLGARARPVRIVAQAAP---ERPAGGGARFTPGGEQQPA
SSFSTGPYQSPNYQ----------------------------------------------
-------AMAAAAGGTVVVQPTTSVSINGE--------VATNGVLTPPQIYEKAAAAGAY
KCNLPWWKIVLLGCVAGCYVGLGGALLLTVGPNCY------GIAQTNPGLAKYITGAI--
---------------------------------------------------------GFP
FALLQIIVCGSELFTGNTA-----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------
>Chl|comp11464_c17_seq3_2-808
-----------------------------------PRSRCCPIACNPPRIGRSIAASRTA
ASSMQAAQIRGCGALPMRASVRLGARARPVRIVAQAAP---ERPAGGGARFTPGGEQQPA
SSFSTGPYQSPNYQGAQPPAAATPADAPAGRSMAATSFSVPPFQSSAYQGAPPAAANPSA
AGPGSYAAMAAAAGGTVVVQPTTSVSINGE--------VATNGVLTPPQIYEKAAAAGAY
KCNLPWWKIVLLGCVAGCYVGLGGALLLTVGPNCY------GIAQTNPGLAKYITGAI--
---------------------------------------------------------GFP
FALLQIIVCGSELFTGNTA-----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------
