>Chl|comp11503_c1_seq1_1-429
WE------AGVELIPAAGQQMPASSISARGAVRPAISPAPSTIGIAAGWRDAAMVYADF-
-TWIFVCSIPLALFVAYGIGANDVANAFGSSVGAKALTMKQAIVIAAICEFGGAVLLGAG
VTSTIRSNIANLNDFKNKPELYMYGMLCALL-----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------
>Chl|comp11503_c3_seq1_1-846
------------------------------------------------------------
------------------------------------------------------------
-------------------------MLCALLATGIWLLVATYFELPVSTTHSIVGAVIGM
SMVAAGAGSVVWSREID-EFPFLQ-GVSVIIISWFTSPLLAGLGGAILFLFTRHAVLRRK
NSYVLSLWMLPLFTFLTVWIGCFYIIQKGPKLADK-----------VDNSTNAWISTCFA
AG--GALVAGLVGVPLIRRQVARDWEELQKAE---VIPELHGATTD---AGKSGKDTD--
------------------------------------------------------------
------------------SDSGSANVNPGAPGTTETAENVVGAGHPERTPAPLRDMRKSR
IYGALTKSSNFDIHGVI-SEN-----EKVHDLHVNAEQFDKKTELSFK-----YLQVFT-
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------
>Chl|comp11503_c3_seq2_508-1374
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--FSMACGCGTPLFASS-YQQ-----CTAAELGCTDGSADASSTQGFPNPPPCAAQVCTA
C------ANSFAHGSNEVANSVGPL--AAIYQIWRDSEVS-SANTVPTWLLA-IGGAAIT
LGLATFGHKVMQSMGVKMTRLTNSRGFCVELSV---------------------------
AAVIIVASRFGLPMSSTPATVGAIAGVGLLEGRA-GFNFRLFLKFCAGWVFTIFATVGMS
CAFMAQGLYSPNKSCAAQRADVGAYLNTTANAIA-------------------------S
VLSGVGTVANNATLVAQAQNITTLTAGQQVPLLSLW---GPMDTQALALGYLANDTVPML
LQ----------------------------------------------------------
-----------------
>Chl|comp11503_c3_seq6_471-1337
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--FSMACGCGTPLFASS-YQQ-----CTAAELGCTDGSADASSTQGFPNPPPCAAQVCTA
C------ANSFAHGSNEVANSVGPL--AAIYQIWRDSEVS-SANTVPTWLLA-IGGAAIT
LGLATFGHKVMQSMGVKMTRLTNSRGFCVELSV---------------------------
AAVIIVASRFGLPMSSTPATVGAIAGVGLLEGRA-GFNFRLFLKFCAGWVFTIFATVGMS
CAFMAQGLYSPNKSCAAQRADVGAYLNTTANAIA-------------------------S
VLSGVGTVANNATLVAQAQNITTLTAGQQVPLLSLW---GPMDTQALALGYLANDTVPLL
LQ----------------------------------------------------------
-----------------
>Chl|comp11503_c3_seq3_471-2273
------------------------------------------------------MYGAV-
-TWMFVVGILLSIVVGFGLGANDVANMFAPSVAARALTMKQALLVAGVFEFTGAILMGAG
VVDTIRSGITRISYFYDSPDVLAYGMLCAMASTAIWMMLATWWELPVSSTQSIVASIAGM
AIVAEGWNAVVWSAEKD-EFPYLK-GMSSIALSWLFAPIMAGLASLILFVLIRTFVLRAH
NAFQRSIFLLPLFTFLTFFVVTWFIIAKGGIHYGW---------EKTPDSKKAWISAIVA
SG--TCLISIFVGIPMLKRKVQRDLDAQEQSA---AAVPPTPGKDV---GDKVSSGSE--
------------------------------------------------------------
----------------------------QSDEEAAAEQPAEAAKPPSRTPKALEAMRQSR
MWRAMTAAVNHDIHAVV-ETD-----ERVAAIHANSESFDSKAETSFK-----YLQVCTA
C------ANSFAHGSNEVANSVGPL--AAIYQIWRDSEVS-SANTVPTWLLA-IGGAAIT
LGLATFGHKVMQSMGVKMTRLTNSRGFCVELSV---------------------------
AAVIIVASRFGLPMSSTPATVGAIAGVGLLEGRA-GFNFRLFLKFCAGWVFTIFATVGMS
CAFMAQGLYSPNKSCAAQRADVGAYLNTTANAIA-------------------------S
VLSGVGTVANNATLVAQAQNITTLTAGQQVPLLSLW---GPMDTQALALGYLANDTVPLL
LQ----------------------------------------------------------
-----------------
>Chl|comp11503_c3_seq4_508-2310
------------------------------------------------------MYGAV-
-TWMFVVGILLSIVVGFGLGANDVANMFAPSVAARALTMKQALLVAGVFEFTGAILMGAG
VVDTIRSGITRISYFYDSPDVLAYGMLCAMASTAIWMMLATWWELPVSSTQSIVASIAGM
AIVAEGWNAVVWSAEKD-EFPYLK-GMSSIALSWLFAPIMAGLASLILFVLIRTFVLRAH
NAFQRSIFLLPLFTFLTFFVVTWFIIAKGGIHYGW---------EKTPDSKKAWISAIVA
SG--TCLISIFVGIPMLKRKVQRDLDAQEQSA---AAVPPTPGKDV---GDKVSSGSE--
------------------------------------------------------------
----------------------------QSDEEAAAEQPAEAAKPPSRTPKALEAMRQSR
MWRAMTAAVNHDIHAVV-ETD-----ERVAAIHANSESFDSKAETSFK-----YLQVCTA
C------ANSFAHGSNEVANSVGPL--AAIYQIWRDSEVS-SANTVPTWLLA-IGGAAIT
LGLATFGHKVMQSMGVKMTRLTNSRGFCVELSV---------------------------
AAVIIVASRFGLPMSSTPATVGAIAGVGLLEGRA-GFNFRLFLKFCAGWVFTIFATVGMS
CAFMAQGLYSPNKSCAAQRADVGAYLNTTANAIA-------------------------S
VLSGVGTVANNATLVAQAQNITTLTAGQQVPLLSLW---GPMDTQALALGYLANDTVPML
LQ----------------------------------------------------------
-----------------
>Chl|comp11503_c3_seq5_471-1235
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------MHA--------------------------------------LLPCCYA
CRVPRVPASRRLHAPRLASLPASPRLPAPCPQIWRDSEVS-SANTVPTWLLA-IGGAAIT
LGLATFGHKVMQSMGVKMTRLTNSRGFCVELSV---------------------------
AAVIIVASRFGLPMSSTPATVGAIAGVGLLEGRA-GFNFRLFLKFCAGWVFTIFATVGMS
CAFMAQGLYSPNKSCAAQRADVGAYLNTTANAIA-------------------------S
VLSGVGTVANNATLVAQAQNITTLTAGQQVPLLSLW---GPMDTQALALGYLANDTVPLL
LQ----------------------------------------------------------
-----------------
>Chl|comp11503_c3_seq7_508-1272
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------MHA--------------------------------------LLPCCYA
CRVPRVPASRRLHAPRLASLPASPRLPAPCPQIWRDSEVS-SANTVPTWLLA-IGGAAIT
LGLATFGHKVMQSMGVKMTRLTNSRGFCVELSV---------------------------
AAVIIVASRFGLPMSSTPATVGAIAGVGLLEGRA-GFNFRLFLKFCAGWVFTIFATVGMS
CAFMAQGLYSPNKSCAAQRADVGAYLNTTANAIA-------------------------S
VLSGVGTVANNATLVAQAQNITTLTAGQQVPLLSLW---GPMDTQALALGYLANDTVPML
LQ----------------------------------------------------------
-----------------
>Clo|comp102706_c0_seq1_316-852
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--LATYGHHIMRVMGVKMTRLTNSRGFTVEICT---------------------------
AAVVILASRFDLPMSTTPATVGAITGVGLLEGRR-GFNYRLLLKCVIGWVATIIIAVLFS
AAFMAQGIYAPSKAFANQRSTVSTYLNTTSNQIA-------------------------A
LLSAT----GNETLVQQAQSITALTATQQVPVVDLI---PPMNTQAMALTFANDSSVCTW
------------------------------------------------------------
-----------------
>Clo|comp60515_c0_seq1_302-2071
-----------------------------------------------------MVFAEI-
-TWIFVCAIFVAVAVGYALGANDVSETFGPAVGAKALTMKQALLVAAVFEFAGAVLMGSG
VVSTIRSGITNVKYFQDQPDVLAYGMLCAMFATAIWMLIATYWELPVSSTQSIVSSIAGM
AIVAEGWSSVLWSAKKD-SFPYLK-GMSAIVLSWVISPFLAAACSLILFLSIRILVLRHP
NAYERSLYLLPLFTFVAFFISTFFVIAKGGLQFGW---------QNTPDSKKAWISAVVA
SG--TCIISVIVGIPYLKRKVKRDLEEEERAA---VEGAAAAAEQG---KDGKAVSDS--
------------------------------------------------------------
---------------------------------------DEETTGQATTPAMLHAFRQSK
LWKAMTTSINTDIHDTL-ETD-----SELRAIHDHAEVFDHKAETSFK-----HLQVFSA
C------ANAFAHGSNEVANSVGPL--AAIYQIWRDSYVA-PNATQPTWLLA-IGGVSIV
IGLATFGHKVMRAVGVRMTKLSNSRGFSVEIAT---------------------------
AAVVILASRFDLPMSTTHASVGAILGVGLLEGRR-GVNWRILPKFIAGWVATLVVTVLTT
MAFTAQGLYSPSKTCGERSVEVANYLNATSNQIA-------------------------A
FLNSTGAAIGNDTMVQQAQSISSLTAQQQTPIINLL---DPMGTQQQALWYLANDTGACT
W-----------------------------------------------------------
-----------------
>Sel|comp12401_c1_seq1_114-1853
-----------------------------------------------------MVYAEV-
-TWIFAVGVVLAVAVGYGLGANDLANMFGPSVGAKALTLKQAVLVAVVFEFVGAVLMGSG
VTSTIRNGITDYRFFEDQPDILAFGMLCALLATGIWMLTATYWELPVSSTQAITAGVAAM
AIVAEGFGSVKWWVPSN-DFPYMKMSMGFIAISWIVAPLLAAIFSAVLYWVVRAVVLRSS
NAYQRSLFLLPMFTCVTFFVVTFFIIEKGGPQYGW---------DKTPVAKKAWVSAVAA
AG--STLIAGLVGIPLLRRKVERDVAEAAAAA----KSADTAIDLP---ADKAAAADA--
------------------------------------------------------------
-------------------------------------AADEEAGAGAADGSLWGALQRSR
AWRVATAGVNYDIHKIV-DES-----ERVREIHDAAEAFDSKAETSFK-----YLQVCTA
C------ANAFAHGSNEVANAVGPL--AAIYQVWQEASVR-SSSAVPHWLLA-IGAFGIC
FGLATYGHYMIQAMGVKTARLTNSRGFVVELCV---------------------------
AAVVILASRLGLPMSSTPATVGAIAGVGLWEGRR-GFNTRLFLKFCAGWVVTIIATVLLT
MAFTAQGLYSPNKFSANERAIVGAYLNLTATQAA-------------------------G
ALPAS-----------SAQAILSAAAGQKMPILSLL---GPMETQAAALSAFDAAVWPRA
------------------------------------------------------------
-----------------
>Chl|comp6022_c1_seq1_1-1110
----------------------------------------WPTCSTIYHTPANMVYGAV-
-TWIFGCATAVAVFVAYGIGANDVANAFGSSVGAKALTMKQALVVAAICEFGGSVLMGAG
VVGTVRKGIANLDYYYNSPDIFAYGMLCAMMATGIWLLIATFWELPVSTTHSIVGAIIGM
TMVSAGPDAVIWSSSKD-TFPYIG-GVASLCLSWVFSPVLGALLAAFLFFWLRLLVLRHE
NAYQRAFYVLPLFVWLTFFMITIFVIKEGGSRFNW---------ENTPYSKACWIAAIVA
SG--TAVISIGWQLWVVQHKVQKDLAEGQVAE---AADKAGAMEAA---GSPAEEKHE--
------------------------------------------------------------
---------------------------------EGSDKAATPAPSDIATPHRLRDFRKSR
VWSAVTHSANVDIHETI-NTD-----AKVNAIHENAEVFDAKAEGVFK-----YLQV---
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------
>Clo|comp42355_c1_seq1_1-357
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------TPSRLQTFRQSR
VWKAVTAGVNADIHKEI-ETN-----EVVRNIHENVEVFDTKAETSFK-----YLQVCSA
C------ANAFAHGANEVANSVGPL--AAIYQVWQDTSVS-ASPSVPTWLLA-IGGFAIV
LGLATYGH----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------
>Sce|comp20752_c0_seq1_1668-3362
HNRIFVHGLLCISQFVATQPIQYSRLVFVATDHTAHLSDHQNSSKRLESPTHGKMYEAI-
-TWMFAVGFVLALLVAYGLGANDVANMFGPSVGARALTMRQALLVAAIFEFLGAVLMGAG
VADTIRSGITNIEFFTPRPDILAYGMMSALGGTGTWMIAATYWEFPVSSTQAIIASVAGM
AIVAKGWNAVVWTARTP-AFPYMK-GMSFIALSWLVAPFLAGAASCFLFFVIRTFVLRAK
NAYQRSLYVLPVFTFLTFFTVTWFTMVKGGVQYNW---------HKIPDVKKTWISIIIA
AG--TTALSIYPGLYLLKKNVNADLEAEEAAK----ASSDAVITVS---ADSKSVDDV--
------------------------------------------------------------
-------------------------------------------DGAAPAPGLLGSIQRSR
VWTALTYGMNYDIHKVI-DTD-----ERVAEIHANAEVFDRKAELTFK-----YLQVCTA
C------ANAFSHGSNEVANAVGPL--AAIYQVWQTGAIT-SKAPVPTWLLA-IGGLGIC
AGLATFGYTVMRAMGVKMTRLTNSRGFCVELCV---------------------------
AAVVIVASYCNLPMSSTLATVGAIAGVGVWEGRS-GFNALLFVKMVSGWILTIIAAVSLT
CLFMAQGLYAPSRGCPLPSF----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------
>Chl|comp5869_c0_seq1_2184-4268
-----------------------------------------------------MVYAEV-
-TWIFVVATAVAIFVAYGIGANDLANSFGTSVGAGALTMRQALAIAALCEFGGAVLMGSG
VTETIRDQIADLSYFESKPDIYAYGMLAAMFSAGIWLILATYWELPVSSTHTVVGAVVGM
TVVAAGPDAVNWSEKTG-SFPFLG-GVSSILLSWVFSPVLTGGLSFLLFGLLRNLVLRSP
RAYHRAYYVLPLFVFITTFVISMFIIQQGGSRFHW---------DHTPLGKIAWISAIVG
AG--CTVIAVTLQWFVIRKRVERDLKLEIEQE---AARAAAAAALQ---APDIEQQGGEP
GMQLEGMHDELISDILGGADPLSFGFSAKSDTSQSLELAPTVGSGVRPTGLGGASPSGQQ
LGASCAAGAALQAVLMSRSSSGESPGHPSAAKRSSQRAAQPQHHPHHATPAVLKKFRNSA
VWSTLTHGVNYDVHQVA-ETD-----ERIAAIHYHSERFDWKAEGVFK-----YLQVFTA
M------ANSFAHGSNDISNSVGPY--AAIYFVWLHSSINMEESQVPVWILA-IGGVGLV
LGLLTYGYKIMRIIGVKVTRLTNSRGFIVEISG---------------------------
AVVVMLCTRFGLPISTTHCLVGAVAGVGMLEGRQ-GFNWRLLFRFFVGWVMTLVVAALTA
AAFTAQGIYSPNNSTAGRRYEIDVYLQNTTAAIS-------------------------G
LLEGS----GVPAYAAASAAINASQAALPSPLLDVT---KAAEVQLQALQAYQAATTWVL
NATANATG----------------------------------------------------
-----------------
>Chl|comp6022_c0_seq1_2-745
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------FK-----YLQVFTA
C------ANSFAHGSNDVANSIGPY--AAIYSVWQTSSVA-KEAEVPTWILI-VGGAGIV
LGLATYGYKIMRVLGVKMVKLTNSRGFIVEMSS---------------------------
AAIVIIGSRYGLPLSTTHTLVGAVTGVGLLEGKR-GFNGTLLLRFFAGWVATLVVAAITA
AAFAAQGIYAPNRNMGEQRYTTATYLTSTAWSVA-------------------------Q
ANQDTAT----LAWIQANLPNWNATSDSWKPLLNLN---LGIQAQQMALLNDSVPICNGS
PAGNVCTA----------------------------------------------------
-----------------
>Chl|comp6365_c0_seq1_2-1516
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------VGAIIGM
TLVAVGPSAVLWSSNSN-TFPFIG-GVASLCASWLTSPVLGALLSCFSFWLLRTLVLRHD
NAYQRAFYVLPLVAYITFWLLTVLILKECSYRWGV---------NEMSYKTACWIGAIVG
AV--ASAGSVVWQIWHVKRRVDADMKAAEELD---MAAKAAGFDLP---APASLPRRP--
------------------------------------------------------------
-----------GAVAPHGSIDPSETSPPVSVGTGPEGDEALQAEAAGMTPEAFRAWRKSR
MWAALTYQANVDIHQEV-EQN-----AQLRVLHEHSEKFDIRAEGVFK-----YLQIFTA
M------ANSFGHGANNVSNAVGPL--AAIYGVWLTSSAA-EQSKVPDWILV-LGGAGFV
VGLATFGYKIMSVVGVKMTRLTSSRGFIVEFST---------------------------
SIIIVIATRCGLPLSSTHTLVGAVTGVGLLEGKH-GFNRVLLIRFFAGWVATLLVAAITA
AAFTAQGIYAPNRGMDEQRYTTGTYLTASAWSVA-------------------------Q
AINDTATRDAVLAQIMA-LPNWNASSPDWKPLLYLN---EAVAAQQAALQGFGAPVCGST
PAGTVNC-----------------------------------------------------
-----------------
>Chl|comp904_c0_seq1_3-479
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------KPLSRTASGKVVGVLKRT------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------ASQMSMAADSIKNSKAGQAIARNR
VFKWLTYGITYDMHCVL-DVDNEKHNQIAEDIWANAEVFDWRAEAVFK-----YIQVFTA
C------TMSFAHGANDVANAMGPF--AAVYYVWQNAEVPGKKVNVPTWILI-FGGAGIV
TGLATYGWHIMG------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------
>Pan|comp43435_c0_seq1_1055-2533
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------MVRVAVLTGCTAATIFVTVRSGVLRRE
DSYQKSFWVLPIMVLFTTWINIYFVFTKGAKKTFQ------GDGDDWSDGKAAWVAACCA
AG--LALLTAIIALPLLKWRVDKKFALGDEDT---ADEEDAQDQLR---PDDYQR-----
------------------------------------------------------------
----------------------------------------------IGTSSSKFVKAMSS
LRKAAMHGMEVDIHQVV-DDD-----PVVAAIHDNAEMFDPKAEYAFS-----YLQVFSA
I------CVIFAHGAGEVGYMAGPL--AAIWYAVKDGLL-YSKVTAPIWCIL-ISAMGLV
VGLSTYGYNVTRAVGTRMAKLSPSRGFAAELAT---------------------------
ATVIMVAAQYGLPTSSSQCITGAIVGLGLMEGKP-GVNWVFLTRQFASWIATLVVVGLAT
AALFAQGVFSPSISCNKVVGLYEDQVIGTAQSIV-------------------------K
DINSTLFAY--KNASAAGMLPKLNATAWQRMNRSISSYMGRGTNMLDPKKNGT------I
KAENAIIYLGQALSLLQGNTIISLGQQVIAGGAPVCNDPTFNPLWPAY-NATCPAPRTLK
GLRSPYNATRWRS----
>Pan|comp43435_c0_seq2_1055-2533
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------MVRVAVLTGCTAATIFVTVRSGVLRRE
DSYQKSFWVLPIMVLFTTWINIYFVFTKGAKKTFQ------GDGDDWSDGKAAWVAACCA
AG--LALLTAIIALPLLKWRVDKKFALGDEDT---ADEEDAQDQLR---PDDYQR-----
------------------------------------------------------------
----------------------------------------------IGTSSSKFVKAMSS
LRKAAMHGMEVDIHQVV-DDD-----PVVAAIHDNAEMFDPKAEYAFS-----YLQVFSA
I------CVIFAHGAGEVGYMAGPL--AAIWYAVKDGLL-YSKVTAPIWCIL-ISAMGLV
VGLSTYGYNVTRAVGTRMAKLSPSRGFAAELAT---------------------------
ATVIMVAAQYGLPTSSSQCITGAIVGLGLMEGKP-GVNWVFLTRQFASWIATLVVVGLAT
AALFAQGVFSPSISCNKVVGLYEDQVIGTAQSIV-------------------------K
DINSTLFAY--KNASAAGMLPKLNATAWQRMNRSISSYMGRGTNMLDPKKNGT------I
KAENAIIYLGQALSLLQGNTIISLGQQVIAGGAPVCNDPTFNPLWPAY-NATCPAPRTLK
GLRSPYNATRWRS----
>tr|A8JH07|A8JH07_CHLRE.Sodium/phosphate.symporter.OS=Chlamydomonas.reinhardtii.GN=PTB3.PE=4.SV=1
--------------------------------------------------MADYAMPEY-
-LWLVVVGSMAAFAFGWGTGSNDVANAFGTSVGAKTLTLKQAVVIAIIFEFVGALVLGRV
STSTIAGGIANINVFLAEPEVYSYGMVIALTVGFVWQALASYWELNVSATHSIIGAIIGF
SFVFGGANAVNWATPDPASFPPYK-GVVPIVLAWFVSPVLTGLASCTIFLIVRTLVLRRE
NSYVLSFWVLPVMVLLTSWINIYFVFTKGAKKTLA-------SNSDWTDHKAAWVAACCA
AG--LAFLTIVIVLPLLKWKADKKFRLDEEKAAGGADEEAAKAKTK---AEEEA------
------------------------------------------------------------
----------------------------------------------ASENNSKFLKAMTS
LKRAAMHGMEVDIHEVV-EED-----PIVAAIHKNAEVFDPKAEYAFS-----YLQVFSA
I------CVIFAHGAGEVGYMAGPL--ATIWFTVKDGTL-YSKVQAPIWIII-ISALGLV
IGLATYGYNVTRAVGTRMAKLSPTRGFSAELST---------------------------
ALVIMVAAQYGLPTSSSQCITGGIVGLGMIEGKT-GVNWMFLLRTFASWIATVVVVALTT
AAIFAMGVFAPSISCNKQLYLYERYTIQQGQSIA-------------------------K
DVLSTLNAY-KTFAYQNTTLPNLNQTKWQAMNKSINAYISNGTKFLTYKSYGS------L
NPQTTNSYLSAAITLMASTSITTLGQAQTYPTAKVCNDNSTLPMTF---NQACKAPQPMK
AIGSEYGFNITTV----
>tr|A8ILI7|A8ILI7_CHLRE.Sodium/phosphate.symporter.OS=Chlamydomonas.reinhardtii.GN=PTB7.PE=4.SV=1
---------------------------------------------------MAAELPEL-
-LWLVVCGSMAAFAFGWATGANDVANAFGTSVGAKTLTLRQAVLLAAAFEFTGALVLGRV
STSTIAGGIASIDFFLRDPEIYAYGMVCALAVGFVWQGLASYWEMNVSATHAIIGAIMGF
SLVYGGRAAVNWASPDPTSFPPYN-GVVPIIA----------------------------
--------------------NMYFVFTKGARKMLAEHHASAGGGKDWSDATSLWVSGVIS
VA--AAAICALAAVPLLRRRAASHFAPGGGG-----------------------------
------------------------------------------------------------
----------------------------------------------ISRDSSRSALLAER
IRKAAMYGMEVDIHQVV-EED-----PLVAAIHAGAEEFDARAEYVFS-----YLQVFSA
I------CVIFAHGAGEVGYMAGPL--ATVYAVYATGTL-PLKVAAPVWCVL-VSAFGLV
TGLATYGYQVTRAMGTRMAKLTPSRGFCAELAT---------------------------
ALVILVASQYGLPTSSSQCITGGIVGVGLLEGLG-GVNWGFFGKTFASWVSTLLICAGAT
AALFAQGVHAPSISHTRHLAVYEDRVLGLGNSLF-------------------------R
EINDTLHRFPPGGSSANPHLTRLPAGTVELLDTAIRQHVDIAQRYRQYRSQGT------V
APDVVMAYLEKALALLQSQSIVTLGQQTVYPGAALCNDGSFDPGHPATGRQPCATPALLR
TAPYPVNMTTFP-----
>Sel|comp8640_c0_seq1_537-2465
--------------------------------------------------MAVPALPQY-
-AWLVVMGAFGAFGFGWGTGANDVANAFGTSVGAKTLTLRQATVIAAIFEFAGALLLGRV
VTNTIAGGIADPKVFARSPEIYAYGMVCALAVGAIWQAVASFAGYNVSSTHTIIGGILGF
ALVYRGSSAVQWATPDPASFPPYK-GVVPIIMSWFFSPVLTAASSALIFSVLRSAVLRRN
NAYNLAFYVLPIAVFITTFINVFFVFTKGAAKTLG---------ADFTSHTSAWLSAAIA
GG--CCALTAFVVVPLLRRRAAHVHAKADADA--AAAAEAAANGLKDPSATMIAVEEA--
------------------------------------------------------------
--------------------------------------------SDNPADQPWYKRALRG
AKAAALYGTSVDIHKAV-EED-----EMIAAIHAHAEKFDPKTEMIFG-----YLQVFSA
I------AVIFAHGAGEVGFMAGPL--SAIYDIYMNGRL-SKAVQSQIWCVA-LSAASLV
IGLATYGYNVTRAMGISLAKLSPSRGFAAELST---------------------------
ALVILVASQLGLPTSSSQCITGGIVGVGLLEGAAKGVNWRQFGKQFASWVATLFVVGLGV
AAIFAQGIYSPSKVDGDAVMAYEKDVAGLTSNIA-------------------------G
GLNETLLGF--ESASRAGLLRNLSPMQWTELNSTVSEL---GTKAANVTSAGT------V
DGKKLISALKQALEIVQNNSILTLGQNEVFPDALICHGHIPANIRGDLPAACPHPLLT--
-----------------
>Sel|comp8640_c0_seq2_537-2465
--------------------------------------------------MAVPALPQY-
-AWLVVMGAFGAFGFGWGTGANDVANAFGTSVGAKTLTLRQATVIAAIFEFAGALLLGRV
VTNTIAGGIADPKVFARSPEIYAYGMVCALAVGAIWQAVASFAGYNVSSTHTIIGGILGF
ALVYRGSSAVQWATPDPASFPPYK-GVVPIIMSWFFSPVLTAASSALIFSVLRSAVLRRN
NAYNLAFYVLPIAVFITTFINVFFVFTKGAAKTLG---------ADFTSHTSAWLSAAIA
GG--CCALTAFVVVPLLRRRAAHVHAKADADA--AAAAEAAANGLKDPSATMIAVEEA--
------------------------------------------------------------
--------------------------------------------SDNPADQPWYKRALRG
AKAAALYGTSVDIHKAV-EED-----EMIAAIHAHAEKFDPKTEMIFG-----YLQVFSA
I------AVIFAHGAGEVGFMAGPL--SAIYDIYMNGRL-SKAVQSQIWCVA-LSAASLV
IGLATYGYNVTRAMGISLAKLSPSRGFAAELST---------------------------
ALVILVASQLGLPTSSSQCITGGIVGVGLLEGAAKGVNWRQFGKQFASWVATLFVVGLGV
AAIFAQGIYSPSKVDGDAVMAYEKDVAGLTSNIA-------------------------G
GLNETLLGF--ESASRAGLLRNLSPMQWTELNSTVSEL---GTKAANVTSAGT------V
DGKKLISALKQALEIVQNNSILTLGQNEVFPDALICHGHIPANIRGDLPAACPHPLLT--
-----------------
>Sel|comp8640_c0_seq3_537-2465
--------------------------------------------------MAVPALPQY-
-AWLVVMGAFGAFGFGWGTGANDVANAFGTSVGAKTLTLRQATVIAAIFEFAGALLLGRV
VTNTIAGGIADPKVFARSPEIYAYGMVCALAVGAIWQAVASFAGYNVSSTHTIIGGILGF
ALVYRGSSAVQWATPDPASFPPYK-GVVPIIMSWFFSPVLTAASSALIFSVLRSAVLRRN
NAYNLAFYVLPIAVFITTFINVFFVFTKGAAKTLG---------ADFTSHTSAWLSAAIA
GG--CCALTAFVVVPLLRRRAAHVHAKADADA--AAAAEAAANGLKDPSATMIAVEEA--
------------------------------------------------------------
--------------------------------------------SDNPADQPWYKRALRG
AKAAALYGTSVDIHKAV-EED-----EMIAAIHAHAEKFDPKTEMIFG-----YLQVFSA
I------AVIFAHGAGEVGFMAGPL--SAIYDIYMNGRL-SKAVQSQIWCVA-LSAASLV
IGLATYGYNVTRAMGISLAKLSPSRGFAAELST---------------------------
ALVILVASQLGLPTSSSQCITGGIVGVGLLEGAAKGVNWRQFGKQFASWVATLFVVGLGV
AAIFAQGIYSPSKVDGDAVMAYEKDVAGLTSNIA-------------------------G
GLNETLLGF--ESASRAGLLRNLSPMQWTELNSTVSEL---GTKAANVTSAGT------V
DGKKLISALKQALEIVQNNSILTLGQNEVFPDALICHGHIPANIRGDLPAACPHPLLT--
-----------------
>Tet|comp15793_c0_seq1_3-776
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------V
IGLATYGYNVTRAMGTMMANLSPSRGFAAELAT---------------------------
ALVVLVASQLALPTSSNQCITGGIVGVGLMEGALKGVNWKHFAKQFLSWVATLFVVGLGV
AALFAQGVYSPSKIDGNQAILYEDRVSNLSSNMY-------------------------K
NFNSTLQDY--EGAAQAGVLTQLPASKWAELNETVNTQAGIIKNLTAKAASSV------V
TPENNMNHLYRALDLYQQYSIFTLGQNKVFPGANVCNSGDAAEIAANS-MIECPAPQFVP
SWVELLPPYPEPVQGSP
>Pan|comp43435_c0_seq2_2482-3012
--------------------------------------------------MTDFVEAEY-
-LWLVVVGSFAAFAFGWGTGSNDVANAFGTSVGAKTLTLKQAVVIAGIFEFTGALVLGRV
STSTIAGGIANIKVFEREPEIYAYGMVCALTTGFVWQSLASYWELNVSATHSIIGAIMGF
SLVYGGADAVNWATADKSSFPPYK-GVVPIVLSWFVSPSSPA------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------APRQPSS--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------
>Sce|comp12500_c0_seq1_2-511
-----------------------------------------------------MAWPQY-
-TWMIVVHGIVAFMDAYGIGANDVANAFGTSVGSKTLSLWSAVCIAAVFEFLGALLLGGQ
VTKTIAGGIAKTSTFAKAPQLFMYGMLTAETGAMIWILLATYMELPVSTTHSIIGGIIGF
ALVFGGGNAVIWYEPKA-DFPYVG-GIVPIIISWFLSPLMAALITLV-------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------
>Tet|comp22329_c3_seq1_186-848
-----------------------------------------------------MALQGY-
-LWILVLHAIVAWLDAYGIGANDVANAFGTSVGSKTLKIWMAVCIAAVFEFTGAVTLGGS
VTKTVAGSIANTSTFEGSPAVFMYGMFCAETGAMVWILLATYLELPVSTTHSIIGGIMGF
SLVFAGAKGVNWSKKTS-EFPYTS-GFVPVVLSWFISPIASAIVSGIIFFLIRTLVLRRK
NSTKVAIWTLPVFLLITVFINLFFILTKGVKATVKIP-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------
>Sce|comp171173_c0_seq1_1-375
---------------------------------HACLFTVQSTQGTFTDNRTKMAWTEY-
-TWMIVIHGIVAWLDAYGIGANDVANSFGTSVGSKTLKLWSAVVIAAIFEFLGAMTLGGQ
VTRTIAGGIARPQTFAKFPALFMFGMLTAETAAMIWILLA--------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------
>Sce|comp15753_c2_seq1_152-985
-----------------------------------------------------MAWTTY-
-THLIVIHGIVAWLDAYGIGANDVANAFGTSVGSRTLKLWAAVCIAAVFEFLGAMLLGGS
VTKTIAGGIAKPGTFKAYPALFMFGMLTAETGAMIWLLLATYLELPVSTTHSIALRIAVT
ISNLGHHKKL---------------LLVPLRCSGWHHRLQPGVWWRLCRHVVR-------
----------------------------------------------AQARQPAW------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------RHRADCHQLVP
VPHCCCTGVPADLPA--------------------------------------HPHVRAA
SPQLHQDCILGAACAHHRNNLGEPLLHSDQGRAWHRQHRDRHRSMDCCCVCRRCCHHGLC
HFVACYEEQGSQV-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------
>Sce|comp12500_c1_seq1_1812-3077
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------IVRTLVLRRA
NSTKIAFYVLPVLILLTFFINLFFILTKGVKGIVS-----------ISPEDGAWYAAAGA
AG--ATLIGTAIIWPLMKRSLANFDNANANSL---EAG-----KDG---SSAFVEEDR--
------------------------------------------------------------
---------------------------------FQRAIAEKLKPVHVDEDDKSVSAMFKR
FRNAALSGVTHDIHADV-KDD-----AGIMEMHEAAEKFDPRTEHVFK-----VLQVISA
C------AMSFAHGANDVANAIGSF--CASLYVYNNLQVPGSNSEVYQWVLA-LGGAGIV
IGLATYGFNIMRVLGVKCAHITPSRGFAMETAT---------------------------
ALVVSIGSAVALPLSTTHTITGATAGGGIAEGRWKALNWPLYGKIMLGWMGTLAAAGCMS
ALLFAVGVYTPSQPQTMELISARNFALANTNATL-------------------------D
RLSALNAAAAAPNATLADQIAAVNASL---------------------LSLGSLDGKSWF
DGSALQKTFQSALDLSSNATVLG-------------------------------------
-----------------
>Sce|comp15753_c2_seq1_933-1676
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------MGSAILWPVMRSKVRKYDAAHDMEA---SK-----DEHG---RHRDVEEDE--
------------------------------------------------------------
---------------------------------FQKRVANYLKAKPVDPEDKSFKAYRTR
FRNAAFSGLSHDIHADI-DGH-----QGLQDMHAGAEKFDPRTEQVFK-----MLQVISA
C------AMSFAHGANDVANAIGSF--AAAYYVYETRTVPGSNSVVFPWILA-LGATGIV
VGLATYGYNIMRVLGVKCVHITPSRGFAMELST---------------------------
SLVIAVGSAYGLPLSTTHTITGATAGGGLAEGRARAISWWLYAKMFA-------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------
>Sce|comp15753_c2_seq2_152-1603
-----------------------------------------------------MAWTTY-
-THLIVIHGIVAWLDAYGIGANDVANAFGTSVGSRTLKLWAAVCIAAVFEFLGAMLLGGS
VTKTIAGGIAKPGTFKAYPALFMFGMLTAETGAMIWLLLATYLELPVSTTHSIVGGIIGF
SLAYGGGSAVTWYEPKPGSLP--G-GIVPIVISWFLSPIAAALVCLLIFLLIRTFVLRRP
NSTKIAFWVLPVLIIVTIWVNLFFILTKGVRGIAS-----------IETDTAAWIAAVSA
VG--AAIMGSAILWPVMRSKVRKYDAAHDMEA---SK-----DEHG---RHRDVEEDE--
------------------------------------------------------------
---------------------------------FQKRVANYLKAKPVDPEDKSFKAYRTR
FRNAAFSGLSHDIHADI-DGH-----QGLQDMHAGAEKFDPRTEQVFK-----MLQVISA
C------AMSFAHGANDVANAIGSF--AAAYYVYETRTVPGSNSVVFPWILA-LGATGIV
VGLATYGYNIMRVLGVKCVHITPSRGFAMELST---------------------------
SLVIAVGSAYGLPLSTTHTITGATAGGGLAEGRARAISWWLYAKMFA-------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------
>Sce|comp17080_c0_seq1_1-972
------------------------------------------------------------
------------------------------------------------------------
---------------------------------MIWILLATYWELPVSTTHSIIGGIIGF
ALAFGGGKAVSWYEPRP-DFPYVR-GIVPIVISWFLSPLLAALITLVFFLLIRTFVLRRQ
NSTKIAFYVLPLLIFITIFISLLFVLTKGVSAVIK-----------ISTEKAAWISAVSG
VG--VALIGTVALWPLMKRMVAKYDREHTGSK---DSGDVVIDAGG---KFKDPEEDE--
------------------------------------------------------------
---------------------------------FQKKVDRALSAKEVDPSDKSFGAYFTR
FRNAALSGVTHDIHADI-KED------KVQEMHDDAEKFDPRTEEVFK-----VLQVISA
C------AMSFSHGANDVANAIGSF--AAALMVYKTFKVPSSNSEVELWILA-LGGTGIV
VGLATYGYNIMRVL----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------
>Tet|comp22329_c0_seq1_2-886
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------PYTTGAWISAVVA
AG--VAAI-ACLFFPFLRRAAARVDAEGNPTD---VE------KVA---PDGEYDEGT--
------------------------------------------------------------
---------------------------------WQKKVADRLKPKHVDPEDKSMGAKLTR
ARNAMLVGVSTDIHEEI-GRD-----AQTTAMHDAAEKFDPRTEQIFK-----YLQVLSA
C------AVSFSHGANDVANAIGSF--TAALATYQTGEVPGKEVNVAIWVLV-LGATGIV
VGLATYGYNIMKVLGVKCTHITPSRGFSMETAT---------------------------
SFVVSVGSVFGLPLSTTHTICGATAGAGLVEGRLDAISWKVYGKMFCGWVVTLIFAAACS
AAIFAYGIYTPSMQATPR------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------
>Sel|comp8589_c2_seq1_167-1975
-----------------------------------------------------MVLNAA-
-LWMVVVGGVVAWVMAYGIGANDVANAFATSVGSHTLKLKWAIVIAAIMETLGAILLGGS
VSDTISGGVANPLAFKSTPDVFAYGMMCALTGAAIWLLVATYWELPVSTTHSIVGGVMGF
ALVYGGPSAVVWNKRIS-EFPFVS-GVLAIVLSWFVSPVLAGLISSALFVVLRTFVLRSK
NSAARAIWCLPILLAITIFVNLTFILLKGAKKVIK-----------LPASTSLMICGICA
VG--GAIIGGAIGVPLLFRSKKRWDAVLADHE---ALPEESKDPLA---AVNLSRSKE--
------------------------------------------------------------
----------------------------------GSGLPNFLKTIEVDPEDKSLRAWCTR
ARNALTGGLNADVFACI-GED-----DGLHNIHASAEKFDPRVEQVFK-----YLQVISA
A------AVSFAHGANDVANAVGPF--AAIYGIYQTGAI-STKSAVEPWMLGGIGSTGIV
IGLATWGWRIMRVLGVKMTAITPCRGFTMETTT---------------------------
ALVTAFGSYLGIPLSTTQTHVGSTTGVGLSEGRRDAVKWGLLLKMFAGWVFTLFVGAIIS
GVLFAWGTYAPNISGAAEQNRLAASMAKGMTEML-------------------------G
ALNAT----GVKDAALAPVLAQLNATMNPTVGVFPSTA---------------------T
SATDLANLMDQTNTIFGRYVRLPAWISRTVG-----------------------------
-----------------
>Tet|comp25555_c5_seq1_117-1919
-----------------------------------------------------MEAGAPD
ILWLVVVGGIIAWVMAYGIGANDVANAFATSVGSRTLKLKWAIAIAVVMETTGAIFLGGS
VSSTISGGVADPKTFANTPDIFAYGMLCALTAAAIWLLFATYAELPVSTTHSIVGGVIGF
GLIYGGSKAIIWAGKTS-SFPFYT-GVVVIVASWFISPVLAGLMSYILYTILRLLVLRGP
TAPNKSIWCLPILLFITVFVNLFFILYKGAKNIIK-----------IDIVTAVWVSAAAG
GG--CALLGAAIGVPLLFRQKKTWESTIDEYR---VAGKGVPGVLP---TLRGKPEVV--
------------------------------------------------------------
---------------------------------GKTALPKWMMVKDVDASDKSVAGYVQR
FKNAAFGGLQQDIFEAV-DND-----SSLSDIHDNAERFDPVVEQVFK-----YLQIISA
A------AMSFAHGANDVANAVGPF--AAIYGIYKYGYI-SSKSTVEMWMLAGIGATGIV
VGLATYGWKIVRVLGVKLTAITPCRGFTMETTT---------------------------
ALVTAFGSYLGIPLSTTQTHVGSTTGVGLAEGRKGAVKWSQLLKMFAGWVFTLIVGMVIS
GILFAWGTFAPNKTYGFQILDYQRAIAEATQANL-------------------------A
ALNAANGVPPAELAALNSGFVDLSNSSSKHPWPSTT-----------------------T
PPGDVIPFLNDTTQMVLDNANLAF------------------------------------
-----------------
>Tet|comp25555_c5_seq2_346-2085
------------------------------------------------------------
--------------MAYGIGANDVANAFATSVGSRTLKLKWAIAIAVVMETTGAIFLGGS
VSSTISGGVADPKTFANTPDIFAYGMLCALTAAAIWLLFATYAELPVSTTHSIVGGVIGF
GLIYGGSKAIIWAGKTS-SFPFYT-GVVVIVASWFISPVLAGLMSYILYTILRLLVLRGP
TAPNKSIWCLPILLFITVFVNLFFILYKGAKNIIK-----------IDIVTAVWVSAAAG
GG--CALLGAAIGVPLLFRQKKTWESTIDEYR---VAGKGVPGVLP---TLRGKPEVV--
------------------------------------------------------------
---------------------------------GKTALPKWMMVKDVDASDKSVAGYVQR
FKNAAFGGLQQDIFEAV-DND-----SSLSDIHDNAERFDPVVEQVFK-----YLQIISA
A------AMSFAHGANDVANAVGPF--AAIYGIYKYGYI-SSKSTVEMWMLAGIGATGIV
VGLATYGWKIVRVLGVKLTAITPCRGFTMETTT---------------------------
ALVTAFGSYLGIPLSTTQTHVGSTTGVGLAEGRKGAVKWSQLLKMFAGWVFTLIVGMVIS
GILFAWGTFAPNKTYGFQILDYQRAIAEATQANL-------------------------A
ALNAANGVPPAELAALNSGFVDLSNSSSKHPWPSTT-----------------------T
PPGDVIPFLNDTTQMVLDNANLAF------------------------------------
-----------------
>Pan|comp48812_c0_seq1_161-2041
--------------------------------------------------MYPNNWDDY-
-MWLVIVGFIVSFVMAAGIGANDVANSFGTSVGAKTITLKQACCIAAVFEFAGAIGLGGE
VTKTIAGSIARPAAFQNEPEIFAFGMMVALIAASSWVFFATYLSLAVSTTHAVIGAVMGF
ALVWGGSGAVVWNDKID-EFPYSK-GLVPVICSWFVSPLMAGIMASVLFAFNRGVILRRE
NSTNWAIYSYPALVGITVFINVFFVIYKGAKNVAH-----------WDSNKAAWVAGVVS
GG--CMLLAAFPGIWLLRWAVKRDMERQAQKA---ADAEANANKVK---DDVEDAEAE--
------------------------------------------------------------
-------------------------------------------------PTSKAMKMFNS
LKKATTRGLNQDIHAHV-ETD-----QAVHDMHAAAEVFNPETEQVYK-----YLQVFSA
C------AVSFAHGANDVANAVGPF--VGIWYVYQHWSI-SSSAPTPVWVLA-MGGAGIV
VGLATYGYNIMATLGVGLAKMTPSRGYCAELAT---------------------------
SFTVALASVYGLPISTTQCITGAEMGVGLTDSWRTGVNYKLFMKQILAWVFTLIVAGFLS
AAIFAFGVFAPSLTMSKDINKYETQIRALSESSY-------------------------K
SLNKTNWAIKNAFPSAP---------FDAKLNSTIYSKMSLYKNMFNSKVIGY------V
DPQTLLDELNTTFRTLNNYTVTVTGFNPATKVYTPSGQQLNATLIQVAPYNETLLKQK--
-----------------
>tr|A8J0U0|A8J0U0_CHLRE.Sodium/phosphate.symporter.OS=Chlamydomonas.reinhardtii.GN=PTB9.PE=4.SV=1
--------------------------------------------------MPPEYWTDY-
-MWLVICGALASFAMAWGIGANDVANSFATSVGAKTITLRQACVIAGIFEFAGALGLGGE
VARTIAGSIARPAAFQDMPEMFAYGMLCALISASTWLYIATYLSLAVSTTHSIIGAVLGF
ALVWGGSGAVVWNDRKK-EFPYST-GLVPVVCSWFVSPITAGIAAGILYFFNRLIVLRRQ
NSTTLAIWVFPLLVFLTVFINLFFVIYKGASKVAG-----------WTSHKAAWVSAVVA
AG--LFVLACFPGTWILRRQVTKDMDEAAQKA---ADAEANAGKEK---EGVEEAE----
------------------------------------------------------------
-------------------------------------------------PTSKAMKIFNS
IKKAATRGLDVDIHANV-ETD-----RAVHDLHAAAEVFSPETEQVYK-----YLQVFSA
C------AVAFAHGANDVANAVGPF--AGIYHVYRFWNV-ASNGETPIWVLA-MGGAGIV
VGLATYGYNIIVTLGVGLAKMTPARGYCAELAA---------------------------
GITISVASVYGLPVSTTQIITGAEMGVGLVESVRTGVNYKLLAKQFAAWVFTLIIAGFLS
AAIFAFGAYAPSLTMGKDILKYETSIRNLTTVIY-------------------------R
SLNASNVAVNTSFPGQQ---------FDPTLNRTITTNTRTINNIFNVRSIGY------I
DPTQLATEMNNAYLTYVNYSVITTGFNRSTRAYVPANQPYAASTIEVKPYAVAAPAAGAA
GGR--------------
>tr|A8J0U4|A8J0U4_CHLRE.Sodium/phosphate.symporter.OS=Chlamydomonas.reinhardtii.GN=PTB4.PE=4.SV=1
--------------------------------------------------MPPEYWTDY-
-MWLVIVGFIVSFIMAAGIGANDVANAFGTSVGAKTITLKQACLIASVFEFAGAIGLGGE
VTKTIAGSIARPTAFQDLPEMFAYGMMCALISASTWVFTATYFSLAVSTTHSVIGAVMGF
ALVWGGSGAVVWNDHMD-AFPYSK-GLVPVICSWFVSPLMSGIASAIIFWLNRVCILRRE
NSTNLAIYMYPLLVGVTVFINVFFVIYKGAKNVAH-----------WDSNKAAWVAACIT
AGKRCMLLAIFPGMWLLRRAVTKDMDRAAQKA---ADAEANAGKPK---EEEVEAE----
------------------------------------------------------------
-------------------------------------------------PTSKAMKIFNS
MKKAATRGLNVDIHEHV-EHD-----QTIHDMHAAAEVFSPETEQVYK-----YLQVFSA
C------AVSFAHGANDVANAVGPF--SGIWYVYRFWTI-TSNGDTPIWVMA-MGGAGIV
VGLATYGYNIMMTLGVGLAKMTPSRGFSAELGT---------------------------
SFTVSLASVYGLPISTTQCITGAEMGVGLVEDLRSGVNWKLFAKQVVAWIFTLIVSGFLC
AAIFAYGAYSPSLTMSKDIAKYKKGMTNVTVTLY-------------------------A
QLTKENIAVNKTFGPAY---------FDKYLNATIASQTKALTAMLNTKNIGY------V
DPPMLIAQMNAAITTYQNNSALTTGFNSSSRAYVPAGQPYAATTIQVQPWPTAAPAGGR-
-----------------
>tr|A8J993|A8J993_CHLRE.Sodium/phosphate.symporter.PTB6a.OS=Chlamydomonas.reinhardtii.GN=PTB6b|PTB6a.PE=4.SV=1
--------------------------------------------------MYPNNWDDY-
-MWLVIVGALAAFFMAYGIGANDVANSFGTSVGAKTLTLAQACCIAAIFEFAGAIGLGGE
VAKTIAGSIARPAAFQNNPELFAYGMMCSLIAAGTWVIIATYFCLAVSTTHAVVGAVMGF
ALVWGGKGAVVWNDHKP-EFPYSN-GLVPVICSWFVSPVTAGIASSILFFLNRIFVLRRE
RSTTFAIWVFPVLVYLTVFINVFFVIYKGAKSVAK-----------WSPNKSAWVAAVVA
AG--AFALAVIPGTWLLRRKVARDMEEAAQKA---ADAEANTGKPKTSDDGAEAAEDG--
------------------------------------------------------------
-------------------------------------------------NASKAMQMFNS
LKRAATHGLRQDIHEKV-ESD-----RDFHDLHAAAEVFSPETEQVYK-----YLQVFSA
C------AVSFAHGSNDVANAIGPF--SGIWHVYKFWNV-SSNGETPVWVLA-LGGAGIV
VGLATYGYNIIQTLGVGLAKMTPARGYCAELAA---------------------------
GITISIASVYGLPVSTTQIITGGELGVGLVENIRTGVNWKLLAKQLLGWVFTLIVAGFLC
AALFAYGAYAPSLTMAKDIAVYQNTMRAAATNLN-------------------------K
LMNVSNYAVGATFPTA----------FDKGLNSSINSNLKTLTNMFNTKTIGY------V
DPYQLGQQLNTSIATYLNQSVTVTGFNRSSRAYVPAGAAYPDTTIQVQPNQ---------
-----------------
>tr|A8J994|A8J994_CHLRE.Sodium/phosphate.symporter.PTB6b.OS=Chlamydomonas.reinhardtii.GN=PTB6b|PTB6a.PE=4.SV=1
------------------------------------------------------------
--------------MAYGIGANDVANSFGTSVGAKTLTLAQACCIAAIFEFAGAIGLGGE
VAKTIAGSIARPAAFQNNPELFAYGMMCSLIAAGTWVIIATYFCLAVSTTHAVVGAVMGF
ALVWGGKGAVVWNDHKP-EFPYSN-GLVPVICSWFVSPVTAGIASSILFFLNRIFVLRRE
RSTTFAIWVFPVLVYLTVFINVFFVIYKGAKSVAK-----------WSPNKSAWVAAVVA
AG--AFALAVIPGTWLLRRKVARDMEEAAQKA---ADAEANTGKPKTSDDGAEAAEDG--
------------------------------------------------------------
-------------------------------------------------NASKAMQMFNS
LKRAATHGLRQDIHEKV-ESD-----RDFHDLHAAAEVFSPETEQVYK-----YLQVFSA
C------AVSFAHGSNDVANAIGPF--SGIWHVYKFWNV-SSNGETPVWVLA-LGGAGIV
VGLATYGYNIIQTLGVGLAKMTPARGYCAELAA---------------------------
GITISIASVYGLPVSTTQIITGGELGVGLVENIRTGVNWKLLAKQLLGWVFTLIVAGFLC
AALFAYGAYAPSLTMAKDIAVYQNTMRAAATNLN-------------------------K
LMNVSNYAVGATFPTA----------FDKGLNSSINSNLKTLTNMFNTKTIGY------V
DPYQLGQQLNTSIATYLNQSVTVTGFNRSSRAYVPAGAAYPDTTIQVQPNQ---------
-----------------
>Tet|comp25703_c10_seq1_166-1968
-----------------------------------------------------MVWETY-
-TWIVVMGAVVAFFMAYGIGANDVANSFGTSVGSKALKLWHAVIIAGVCEFLGAMLLGAP
TARTIAGSIAKNSAFERHPEVLMYGMLCALSAAAIWLLVATYLELAVSTTHSIVGAVMGF
SLVFGGGSAIVWAERID-EFPYLR-GVAVIAMSWIISPLACGFIVAIFFLTVRTIVLRPK
NSTKRAFWLLPVLVFITVYINAFFVMFKGAAGKFK--------DLGENPAQCAWIAAVVA
AG--GTLFTLVVIMPFLHKKLQAWIEGSAGPS---KCVFGDAGGVE---AGDAKGVDA--
------------------------------------------------------------
-------------------------------------------SMDLESAKAGKPSFKDR
FMKAATAGIKADIHDTAYEED-----AHAVAVADNAEKFDASTEHVLS-----YLQVFTA
M------CDAFSHGANDVANSIGPF--AAIWQVYTTQMA-TSRSTVPVWILA-IGSLGIV
VGLATYGYKIIRAIGVKLAHITPSRGFCVELGT---------------------------
AWIISLGSMFGLPLSTTHCQVGGTAGVGLVEGRK-GVNWRLLLKTFGAWVMTLVVAGCFS
AALFSAGAFAPSIPMARQIEQYEDGVLASSSEML-------------------------N
VLNSTNLGNCTVPDA---------PTCNVGLNDTISSMGKDISDMLNPKNTQT------L
MPSDVLGVMNSSFGLYQEHSTIDTTP----------------------------------
-----------------
>Pan|comp48280_c0_seq1_933-2198
-----------------------------------------------QQQQQQQQQQQHW
VQWQQPLNGQSQNAGQYGTGQQP-QQRHGSTYGSRQLTQP--------------------
------------------------------------------------------------
-------------------------GPIAEALEW--------------------------
------------------------------------------------------------
----------------ARKSTPPDGDTYEKDS------------VK---DDGEEHDGA--
------------------------------------------------------------
-------------------------------------------GGGQHAGNVQWQNTFDQ
LKAIVLRGTNQNVHEAI-ITD-----PATQRLHAHAEVFDPATEDAFK-----YLQVVTA
I------CDSFSHGANDVANSVGPF--TAIWYIYRYERV-DYMADLPVWILV-LGGAGIV
VGLATYGYNIIRAIGIRLSVITPSRGFCIELST---------------------------
AVVVAVASKYGLPISTTHCQVGATAGMGLTEGGS-GVHWRLALQFFLGWVVTLLITGLLS
AALFAAGAYAPCIQQGRAIMQYEDALLDLTTRID-------------------------L
ILNRTNYAARVDPATWGN--------FSAVLNATLYANLQKLQLMMAPSSSDSTRPVQQI
DQSDLLDFVNSTVNSYYNNSLPYIGGMAATGQVLPRRP----------------------
-----------------
>Pan|comp48033_c3_seq7_372-2378
------------------------------------------------------MWTEY-
-TWIVVTGCLAAFFTAYGIGANDVANAFGSSVAARTLTMRQALLIAAVCEFSGSVLLGGE
VTRTVASGIAKLSSFEREPEMYMYGMLCALVSSGTWLIVATYLELPVSTTHAIAGAVMGF
AFVYGGPSAVVWLEPQD-QFPYMR-GMVPIVVSWFISPLLSALASSLLFVVVRTAILRRE
SSLEIAFWALPVLVMFTVFINCYFVLYKGASKRIK-----------WSSNKCAWVSLVVA
AG--CTLLTVLVGMPLVRQYVYQDMETRRRLQ---LSELESHMKVS---EHQSRADTT--
------------------------------------------------------------
----------------------------------GISGNNSPGNGNGGFPRPLSQNARAT
GGGGRSTGSGGQLPGPA---------AAEKTMQAAAPGFASP-----------FVEYPSP
SQQRQQVARPSMPSPSPAAAPRSPY---GSFTRARTGSGPDRQSSQQ-------------
LGLQTRGASPPPPPEAVQASAKAANGGAAEASEQHGRTSLRRQRQQQLQPGEQQQQQQRD
GGSGEAASGSSLPQVQEDEASPPGLGGG---------------------------TGGSG
GAVLAAPPYVPDQQWQQQQEWSQQQVQQQQQQLGVQPGDPRGPLPGAAPYGLLQPRPRPR
GDHRQHRVVGAAGAGQDGLRGSGDRLIQRRPPGHPGPQPAAAAPRRRPPPSGPQAGRLHR
QPHSHLGPLLLLLRPPDRPGAGGGGAERVRQVPRQRPAPREPHGGRQRPDGVAGVLPCGQ
DAAG-------------
>Chl|comp11503_c1_seq1_1-429
WEAGVELIPAAGQQMPASSISARGAVRPAISPAPSTIGIAAGWRDAAMVYADFTWIFVCSIPLALFVAYGIGANDVANAFGSSVGAKALTMKQAIVIAAICEFGGAVLLGAGVTSTIRSNIANLNDFKNKPELYMYGMLCALL
>Chl|comp11503_c3_seq1_1-846
MLCALLATGIWLLVATYFELPVSTTHSIVGAVIGMSMVAAGAGSVVWSREIDEFPFLQGVSVIIISWFTSPLLAGLGGAILFLFTRHAVLRRKNSYVLSLWMLPLFTFLTVWIGCFYIIQKGPKLADKVDNSTNAWISTCFAAGGALVAGLVGVPLIRRQVARDWEELQKAEVIPELHGATTDAGKSGKDTDSDSGSANVNPGAPGTTETAENVVGAGHPERTPAPLRDMRKSRIYGALTKSSNFDIHGVISENEKVHDLHVNAEQFDKKTELSFKYLQVFT
>Chl|comp11503_c3_seq2_508-1374
FSMACGCGTPLFASSYQQCTAAELGCTDGSADASSTQGFPNPPPCAAQVCTACANSFAHGSNEVANSVGPLAAIYQIWRDSEVSSANTVPTWLLAIGGAAITLGLATFGHKVMQSMGVKMTRLTNSRGFCVELSVAAVIIVASRFGLPMSSTPATVGAIAGVGLLEGRAGFNFRLFLKFCAGWVFTIFATVGMSCAFMAQGLYSPNKSCAAQRADVGAYLNTTANAIASVLSGVGTVANNATLVAQAQNITTLTAGQQVPLLSLWGPMDTQALALGYLANDTVPMLLQ*
>Chl|comp11503_c3_seq3_471-2273
MYGAVTWMFVVGILLSIVVGFGLGANDVANMFAPSVAARALTMKQALLVAGVFEFTGAILMGAGVVDTIRSGITRISYFYDSPDVLAYGMLCAMASTAIWMMLATWWELPVSSTQSIVASIAGMAIVAEGWNAVVWSAEKDEFPYLKGMSSIALSWLFAPIMAGLASLILFVLIRTFVLRAHNAFQRSIFLLPLFTFLTFFVVTWFIIAKGGIHYGWEKTPDSKKAWISAIVASGTCLISIFVGIPMLKRKVQRDLDAQEQSAAAVPPTPGKDVGDKVSSGSEQSDEEAAAEQPAEAAKPPSRTPKALEAMRQSRMWRAMTAAVNHDIHAVVETDERVAAIHANSESFDSKAETSFKYLQVCTACANSFAHGSNEVANSVGPLAAIYQIWRDSEVSSANTVPTWLLAIGGAAITLGLATFGHKVMQSMGVKMTRLTNSRGFCVELSVAAVIIVASRFGLPMSSTPATVGAIAGVGLLEGRAGFNFRLFLKFCAGWVFTIFATVGMSCAFMAQGLYSPNKSCAAQRADVGAYLNTTANAIASVLSGVGTVANNATLVAQAQNITTLTAGQQVPLLSLWGPMDTQALALGYLANDTVPLLLQ*
>Chl|comp11503_c3_seq4_508-2310
MYGAVTWMFVVGILLSIVVGFGLGANDVANMFAPSVAARALTMKQALLVAGVFEFTGAILMGAGVVDTIRSGITRISYFYDSPDVLAYGMLCAMASTAIWMMLATWWELPVSSTQSIVASIAGMAIVAEGWNAVVWSAEKDEFPYLKGMSSIALSWLFAPIMAGLASLILFVLIRTFVLRAHNAFQRSIFLLPLFTFLTFFVVTWFIIAKGGIHYGWEKTPDSKKAWISAIVASGTCLISIFVGIPMLKRKVQRDLDAQEQSAAAVPPTPGKDVGDKVSSGSEQSDEEAAAEQPAEAAKPPSRTPKALEAMRQSRMWRAMTAAVNHDIHAVVETDERVAAIHANSESFDSKAETSFKYLQVCTACANSFAHGSNEVANSVGPLAAIYQIWRDSEVSSANTVPTWLLAIGGAAITLGLATFGHKVMQSMGVKMTRLTNSRGFCVELSVAAVIIVASRFGLPMSSTPATVGAIAGVGLLEGRAGFNFRLFLKFCAGWVFTIFATVGMSCAFMAQGLYSPNKSCAAQRADVGAYLNTTANAIASVLSGVGTVANNATLVAQAQNITTLTAGQQVPLLSLWGPMDTQALALGYLANDTVPMLLQ*
>Chl|comp11503_c3_seq5_471-1235
MHALLPCCYACRVPRVPASRRLHAPRLASLPASPRLPAPCPQIWRDSEVSSANTVPTWLLAIGGAAITLGLATFGHKVMQSMGVKMTRLTNSRGFCVELSVAAVIIVASRFGLPMSSTPATVGAIAGVGLLEGRAGFNFRLFLKFCAGWVFTIFATVGMSCAFMAQGLYSPNKSCAAQRADVGAYLNTTANAIASVLSGVGTVANNATLVAQAQNITTLTAGQQVPLLSLWGPMDTQALALGYLANDTVPLLLQ*
>Chl|comp11503_c3_seq6_471-1337
FSMACGCGTPLFASSYQQCTAAELGCTDGSADASSTQGFPNPPPCAAQVCTACANSFAHGSNEVANSVGPLAAIYQIWRDSEVSSANTVPTWLLAIGGAAITLGLATFGHKVMQSMGVKMTRLTNSRGFCVELSVAAVIIVASRFGLPMSSTPATVGAIAGVGLLEGRAGFNFRLFLKFCAGWVFTIFATVGMSCAFMAQGLYSPNKSCAAQRADVGAYLNTTANAIASVLSGVGTVANNATLVAQAQNITTLTAGQQVPLLSLWGPMDTQALALGYLANDTVPLLLQ*
>Chl|comp11503_c3_seq7_508-1272
MHALLPCCYACRVPRVPASRRLHAPRLASLPASPRLPAPCPQIWRDSEVSSANTVPTWLLAIGGAAITLGLATFGHKVMQSMGVKMTRLTNSRGFCVELSVAAVIIVASRFGLPMSSTPATVGAIAGVGLLEGRAGFNFRLFLKFCAGWVFTIFATVGMSCAFMAQGLYSPNKSCAAQRADVGAYLNTTANAIASVLSGVGTVANNATLVAQAQNITTLTAGQQVPLLSLWGPMDTQALALGYLANDTVPMLLQ*
>Chl|comp5869_c0_seq1_2184-4268
MVYAEVTWIFVVATAVAIFVAYGIGANDLANSFGTSVGAGALTMRQALAIAALCEFGGAVLMGSGVTETIRDQIADLSYFESKPDIYAYGMLAAMFSAGIWLILATYWELPVSSTHTVVGAVVGMTVVAAGPDAVNWSEKTGSFPFLGGVSSILLSWVFSPVLTGGLSFLLFGLLRNLVLRSPRAYHRAYYVLPLFVFITTFVISMFIIQQGGSRFHWDHTPLGKIAWISAIVGAGCTVIAVTLQWFVIRKRVERDLKLEIEQEAARAAAAAALQAPDIEQQGGEPGMQLEGMHDELISDILGGADPLSFGFSAKSDTSQSLELAPTVGSGVRPTGLGGASPSGQQLGASCAAGAALQAVLMSRSSSGESPGHPSAAKRSSQRAAQPQHHPHHATPAVLKKFRNSAVWSTLTHGVNYDVHQVAETDERIAAIHYHSERFDWKAEGVFKYLQVFTAMANSFAHGSNDISNSVGPYAAIYFVWLHSSINMEESQVPVWILAIGGVGLVLGLLTYGYKIMRIIGVKVTRLTNSRGFIVEISGAVVVMLCTRFGLPISTTHCLVGAVAGVGMLEGRQGFNWRLLFRFFVGWVMTLVVAALTAAAFTAQGIYSPNNSTAGRRYEIDVYLQNTTAAISGLLEGSGVPAYAAASAAINASQAALPSPLLDVTKAAEVQLQALQAYQAATTWVLNATANATG*
>Chl|comp6022_c0_seq1_2-745
FKYLQVFTACANSFAHGSNDVANSIGPYAAIYSVWQTSSVAKEAEVPTWILIVGGAGIVLGLATYGYKIMRVLGVKMVKLTNSRGFIVEMSSAAIVIIGSRYGLPLSTTHTLVGAVTGVGLLEGKRGFNGTLLLRFFAGWVATLVVAAITAAAFAAQGIYAPNRNMGEQRYTTATYLTSTAWSVAQANQDTATLAWIQANLPNWNATSDSWKPLLNLNLGIQAQQMALLNDSVPICNGSPAGNVCTA*
>Chl|comp6022_c1_seq1_1-1110
WPTCSTIYHTPANMVYGAVTWIFGCATAVAVFVAYGIGANDVANAFGSSVGAKALTMKQALVVAAICEFGGSVLMGAGVVGTVRKGIANLDYYYNSPDIFAYGMLCAMMATGIWLLIATFWELPVSTTHSIVGAIIGMTMVSAGPDAVIWSSSKDTFPYIGGVASLCLSWVFSPVLGALLAAFLFFWLRLLVLRHENAYQRAFYVLPLFVWLTFFMITIFVIKEGGSRFNWENTPYSKACWIAAIVASGTAVISIGWQLWVVQHKVQKDLAEGQVAEAADKAGAMEAAGSPAEEKHEEGSDKAATPAPSDIATPHRLRDFRKSRVWSAVTHSANVDIHETINTDAKVNAIHENAEVFDAKAEGVFKYLQV
>Chl|comp6365_c0_seq1_2-1516
VGAIIGMTLVAVGPSAVLWSSNSNTFPFIGGVASLCASWLTSPVLGALLSCFSFWLLRTLVLRHDNAYQRAFYVLPLVAYITFWLLTVLILKECSYRWGVNEMSYKTACWIGAIVGAVASAGSVVWQIWHVKRRVDADMKAAEELDMAAKAAGFDLPAPASLPRRPGAVAPHGSIDPSETSPPVSVGTGPEGDEALQAEAAGMTPEAFRAWRKSRMWAALTYQANVDIHQEVEQNAQLRVLHEHSEKFDIRAEGVFKYLQIFTAMANSFGHGANNVSNAVGPLAAIYGVWLTSSAAEQSKVPDWILVLGGAGFVVGLATFGYKIMSVVGVKMTRLTSSRGFIVEFSTSIIIVIATRCGLPLSSTHTLVGAVTGVGLLEGKHGFNRVLLIRFFAGWVATLLVAAITAAAFTAQGIYAPNRGMDEQRYTTGTYLTASAWSVAQAINDTATRDAVLAQIMALPNWNASSPDWKPLLYLNEAVAAQQAALQGFGAPVCGSTPAGTVNC*
>Chl|comp6365_c1_seq1_2-505
DGSAASRFGSQRAPSSPASPKSAAGTLFGARQSGGAAPAPDAIDMVYGAITWIFVCALVLAFVVAYGIGANDVANSFGSSVGARALTMKQAILLASICEFSGAVLMGSSVTETIRTGIAKLDAFHHSPDVLAYGMLCALLASGIWLLVATFWELPVSTTHAIVGAIIG
>Chl|comp904_c0_seq1_3-479
KPLSRTASGKVVGVLKRTASQMSMAADSIKNSKAGQAIARNRVFKWLTYGITYDMHCVLDVDNEKHNQIAEDIWANAEVFDWRAEAVFKYIQVFTACTMSFAHGANDVANAMGPFAAVYYVWQNAEVPGKKVNVPTWILIFGGAGIVTGLATYGWHIMG
>Clo|comp102706_c0_seq1_316-852
LATYGHHIMRVMGVKMTRLTNSRGFTVEICTAAVVILASRFDLPMSTTPATVGAITGVGLLEGRRGFNYRLLLKCVIGWVATIIIAVLFSAAFMAQGIYAPSKAFANQRSTVSTYLNTTSNQIAALLSATGNETLVQQAQSITALTATQQVPVVDLIPPMNTQAMALTFANDSSVCTW*
>Clo|comp42355_c0_seq1_1-750
LKFHSWVATSVHSPGIAQRPTMVYAEVTWIFVCAIFLAILVGWGLGANDVANTFGPSVGARALTLKQAVLVAAIFEFAGAVLMGSGVTTTIRSGITNISYFVDQPDILAYGMLCAMLATGLWMLIATYWELPVSSTQSIVASIAGMTIVAEGFDAVIWSAEKDSFPYLKGMSAIVLSWLISPLLAGGFSLILFFLIRALVLRHKNAYQRSIVLLPLFTFITFFVVTYFTIAKGGLHYNWNKTPDSKKAWI
>Clo|comp42355_c1_seq1_1-357
TPSRLQTFRQSRVWKAVTAGVNADIHKEIETNEVVRNIHENVEVFDTKAETSFKYLQVCSACANAFAHGANEVANSVGPLAAIYQVWQDTSVSASPSVPTWLLAIGGFAIVLGLATYGH
>Clo|comp60515_c0_seq1_302-2071
MVFAEITWIFVCAIFVAVAVGYALGANDVSETFGPAVGAKALTMKQALLVAAVFEFAGAVLMGSGVVSTIRSGITNVKYFQDQPDVLAYGMLCAMFATAIWMLIATYWELPVSSTQSIVSSIAGMAIVAEGWSSVLWSAKKDSFPYLKGMSAIVLSWVISPFLAAACSLILFLSIRILVLRHPNAYERSLYLLPLFTFVAFFISTFFVIAKGGLQFGWQNTPDSKKAWISAVVASGTCIISVIVGIPYLKRKVKRDLEEEERAAVEGAAAAAEQGKDGKAVSDSDEETTGQATTPAMLHAFRQSKLWKAMTTSINTDIHDTLETDSELRAIHDHAEVFDHKAETSFKHLQVFSACANAFAHGSNEVANSVGPLAAIYQIWRDSYVAPNATQPTWLLAIGGVSIVIGLATFGHKVMRAVGVRMTKLSNSRGFSVEIATAAVVILASRFDLPMSTTHASVGAILGVGLLEGRRGVNWRILPKFIAGWVATLVVTVLTTMAFTAQGLYSPSKTCGERSVEVANYLNATSNQIAAFLNSTGAAIGNDTMVQQAQSISSLTAQQQTPIINLLDPMGTQQQALWYLANDTGACTW*
>Cos|comp35792_c0_seq1_106-1890
MAAMPQALTSSRTLSLSRHTLRSREHLRVPPEQSAQKRQTRRVTAASSFQERPGLHPLCKWETQKQGIRSRHQDTTRANSVSDSSSSVPVNFLNDQVFQSDVEEPLTAPGTNGAASSGPPADGPQGMAEAFKISPQSASTIITVVTCAAFVLPLVLNVCVAGASVTTRGLGYLTMLLGFYMAWNIGANDVANAMGTSVGSGALSLRQAVLTAAILEFGGAFLVGSHVSHTMQSGIVNSAMFAARPHVLFCGMLASLAAAGTWLQVASFYGWPVSTTHCIIGAMVGFGLVHGGWGAVYWTSLARVVSSWLISPLFGACIAYIVYRCIRTFVYDASNPGQAACRAAPALVFLGVTAFSLSSLVTGGALWWPLIQSLMAGTVGAVIVSALIDRQLGELLGDFCEIPGKMQPTRVNPRGPTGTQLRIVYVVFGYLQVLSACFMSFAHGANDVANAIGPILAALAILQGPGAPPLPDTVATRVLVWGGFGIVAGLLVWGYRVIATIGKGITELTPTRGFAAEFSAATVVVVASRMGLPISATHTLVGAVMGVGLARGLNSVRFDVMKDIAASWVVTIPIGATLSIVYSFILLRVLPNVL*
>Pan|comp43435_c0_seq1_1055-2533
MVRVAVLTGCTAATIFVTVRSGVLRREDSYQKSFWVLPIMVLFTTWINIYFVFTKGAKKTFQGDGDDWSDGKAAWVAACCAAGLALLTAIIALPLLKWRVDKKFALGDEDTADEEDAQDQLRPDDYQRIGTSSSKFVKAMSSLRKAAMHGMEVDIHQVVDDDPVVAAIHDNAEMFDPKAEYAFSYLQVFSAICVIFAHGAGEVGYMAGPLAAIWYAVKDGLLYSKVTAPIWCILISAMGLVVGLSTYGYNVTRAVGTRMAKLSPSRGFAAELATATVIMVAAQYGLPTSSSQCITGAIVGLGLMEGKPGVNWVFLTRQFASWIATLVVVGLATAALFAQGVFSPSISCNKVVGLYEDQVIGTAQSIVKDINSTLFAYKNASAAGMLPKLNATAWQRMNRSISSYMGRGTNMLDPKKNGTIKAENAIIYLGQALSLLQGNTIISLGQQVIAGGAPVCNDPTFNPLWPAYNATCPAPRTLKGLRSPYNATRWRS*
>Pan|comp43435_c0_seq2_2482-3012
MTDFVEAEYLWLVVVGSFAAFAFGWGTGSNDVANAFGTSVGAKTLTLKQAVVIAGIFEFTGALVLGRVSTSTIAGGIANIKVFEREPEIYAYGMVCALTTGFVWQSLASYWELNVSATHSIIGAIMGFSLVYGGADAVNWATADKSSFPPYKGVVPIVLSWFVSPSSPAAPRQPSS*
>Pan|comp43435_c0_seq2_1055-2533
MVRVAVLTGCTAATIFVTVRSGVLRREDSYQKSFWVLPIMVLFTTWINIYFVFTKGAKKTFQGDGDDWSDGKAAWVAACCAAGLALLTAIIALPLLKWRVDKKFALGDEDTADEEDAQDQLRPDDYQRIGTSSSKFVKAMSSLRKAAMHGMEVDIHQVVDDDPVVAAIHDNAEMFDPKAEYAFSYLQVFSAICVIFAHGAGEVGYMAGPLAAIWYAVKDGLLYSKVTAPIWCILISAMGLVVGLSTYGYNVTRAVGTRMAKLSPSRGFAAELATATVIMVAAQYGLPTSSSQCITGAIVGLGLMEGKPGVNWVFLTRQFASWIATLVVVGLATAALFAQGVFSPSISCNKVVGLYEDQVIGTAQSIVKDINSTLFAYKNASAAGMLPKLNATAWQRMNRSISSYMGRGTNMLDPKKNGTIKAENAIIYLGQALSLLQGNTIISLGQQVIAGGAPVCNDPTFNPLWPAYNATCPAPRTLKGLRSPYNATRWRS*
>Pan|comp48033_c3_seq7_372-2378
MWTEYTWIVVTGCLAAFFTAYGIGANDVANAFGSSVAARTLTMRQALLIAAVCEFSGSVLLGGEVTRTVASGIAKLSSFEREPEMYMYGMLCALVSSGTWLIVATYLELPVSTTHAIAGAVMGFAFVYGGPSAVVWLEPQDQFPYMRGMVPIVVSWFISPLLSALASSLLFVVVRTAILRRESSLEIAFWALPVLVMFTVFINCYFVLYKGASKRIKWSSNKCAWVSLVVAAGCTLLTVLVGMPLVRQYVYQDMETRRRLQLSELESHMKVSEHQSRADTTGISGNNSPGNGNGGFPRPLSQNARATGGGGRSTGSGGQLPGPAAAEKTMQAAAPGFASPFVEYPSPSQQRQQVARPSMPSPSPAAAPRSPYGSFTRARTGSGPDRQSSQQLGLQTRGASPPPPPEAVQASAKAANGGAAEASEQHGRTSLRRQRQQQLQPGEQQQQQQRDGGSGEAASGSSLPQVQEDEASPPGLGGGTGGSGGAVLAAPPYVPDQQWQQQQEWSQQQVQQQQQQLGVQPGDPRGPLPGAAPYGLLQPRPRPRGDHRQHRVVGAAGAGQDGLRGSGDRLIQRRPPGHPGPQPAAAAPRRRPPPSGPQAGRLHRQPHSHLGPLLLLLRPPDRPGAGGGGAERVRQVPRQRPAPREPHGGRQRPDGVAGVLPCGQDAAG*
>Pan|comp48280_c0_seq1_933-2198
QQQQQQQQQQQHWVQWQQPLNGQSQNAGQYGTGQQPQQRHGSTYGSRQLTQPGPIAEALEWARKSTPPDGDTYEKDSVKDDGEEHDGAGGGQHAGNVQWQNTFDQLKAIVLRGTNQNVHEAIITDPATQRLHAHAEVFDPATEDAFKYLQVVTAICDSFSHGANDVANSVGPFTAIWYIYRYERVDYMADLPVWILVLGGAGIVVGLATYGYNIIRAIGIRLSVITPSRGFCIELSTAVVVAVASKYGLPISTTHCQVGATAGMGLTEGGSGVHWRLALQFFLGWVVTLLITGLLSAALFAAGAYAPCIQQGRAIMQYEDALLDLTTRIDLILNRTNYAARVDPATWGNFSAVLNATLYANLQKLQLMMAPSSSDSTRPVQQIDQSDLLDFVNSTVNSYYNNSLPYIGGMAATGQVLPRRP*
>Pan|comp48812_c0_seq1_161-2041
MYPNNWDDYMWLVIVGFIVSFVMAAGIGANDVANSFGTSVGAKTITLKQACCIAAVFEFAGAIGLGGEVTKTIAGSIARPAAFQNEPEIFAFGMMVALIAASSWVFFATYLSLAVSTTHAVIGAVMGFALVWGGSGAVVWNDKIDEFPYSKGLVPVICSWFVSPLMAGIMASVLFAFNRGVILRRENSTNWAIYSYPALVGITVFINVFFVIYKGAKNVAHWDSNKAAWVAGVVSGGCMLLAAFPGIWLLRWAVKRDMERQAQKAADAEANANKVKDDVEDAEAEPTSKAMKMFNSLKKATTRGLNQDIHAHVETDQAVHDMHAAAEVFNPETEQVYKYLQVFSACAVSFAHGANDVANAVGPFVGIWYVYQHWSISSSAPTPVWVLAMGGAGIVVGLATYGYNIMATLGVGLAKMTPSRGYCAELATSFTVALASVYGLPISTTQCITGAEMGVGLTDSWRTGVNYKLFMKQILAWVFTLIVAGFLSAAIFAFGVFAPSLTMSKDINKYETQIRALSESSYKSLNKTNWAIKNAFPSAPFDAKLNSTIYSKMSLYKNMFNSKVIGYVDPQTLLDELNTTFRTLNNYTVTVTGFNPATKVYTPSGQQLNATLIQVAPYNETLLKQK*
>Sce|comp12500_c0_seq1_2-511
MAWPQYTWMIVVHGIVAFMDAYGIGANDVANAFGTSVGSKTLSLWSAVCIAAVFEFLGALLLGGQVTKTIAGGIAKTSTFAKAPQLFMYGMLTAETGAMIWILLATYMELPVSTTHSIIGGIIGFALVFGGGNAVIWYEPKADFPYVGGIVPIIISWFLSPLMAALITLV
>Sce|comp12500_c1_seq1_1812-3077
IVRTLVLRRANSTKIAFYVLPVLILLTFFINLFFILTKGVKGIVSISPEDGAWYAAAGAAGATLIGTAIIWPLMKRSLANFDNANANSLEAGKDGSSAFVEEDRFQRAIAEKLKPVHVDEDDKSVSAMFKRFRNAALSGVTHDIHADVKDDAGIMEMHEAAEKFDPRTEHVFKVLQVISACAMSFAHGANDVANAIGSFCASLYVYNNLQVPGSNSEVYQWVLALGGAGIVIGLATYGFNIMRVLGVKCAHITPSRGFAMETATALVVSIGSAVALPLSTTHTITGATAGGGIAEGRWKALNWPLYGKIMLGWMGTLAAAGCMSALLFAVGVYTPSQPQTMELISARNFALANTNATLDRLSALNAAAAAPNATLADQIAAVNASLLSLGSLDGKSWFDGSALQKTFQSALDLSSNATVLG*
>Sce|comp15753_c2_seq1_152-985
MAWTTYTHLIVIHGIVAWLDAYGIGANDVANAFGTSVGSRTLKLWAAVCIAAVFEFLGAMLLGGSVTKTIAGGIAKPGTFKAYPALFMFGMLTAETGAMIWLLLATYLELPVSTTHSIALRIAVTISNLGHHKKLLLVPLRCSGWHHRLQPGVWWRLCRHVVRAQARQPAWRHRADCHQLVPVPHCCCTGVPADLPAHPHVRAASPQLHQDCILGAACAHHRNNLGEPLLHSDQGRAWHRQHRDRHRSMDCCCVCRRCCHHGLCHFVACYEEQGSQV*
>Sce|comp15753_c2_seq1_933-1676
MGSAILWPVMRSKVRKYDAAHDMEASKDEHGRHRDVEEDEFQKRVANYLKAKPVDPEDKSFKAYRTRFRNAAFSGLSHDIHADIDGHQGLQDMHAGAEKFDPRTEQVFKMLQVISACAMSFAHGANDVANAIGSFAAAYYVYETRTVPGSNSVVFPWILALGATGIVVGLATYGYNIMRVLGVKCVHITPSRGFAMELSTSLVIAVGSAYGLPLSTTHTITGATAGGGLAEGRARAISWWLYAKMFA
>Sce|comp15753_c2_seq2_152-1603
MAWTTYTHLIVIHGIVAWLDAYGIGANDVANAFGTSVGSRTLKLWAAVCIAAVFEFLGAMLLGGSVTKTIAGGIAKPGTFKAYPALFMFGMLTAETGAMIWLLLATYLELPVSTTHSIVGGIIGFSLAYGGGSAVTWYEPKPGSLPGGIVPIVISWFLSPIAAALVCLLIFLLIRTFVLRRPNSTKIAFWVLPVLIIVTIWVNLFFILTKGVRGIASIETDTAAWIAAVSAVGAAIMGSAILWPVMRSKVRKYDAAHDMEASKDEHGRHRDVEEDEFQKRVANYLKAKPVDPEDKSFKAYRTRFRNAAFSGLSHDIHADIDGHQGLQDMHAGAEKFDPRTEQVFKMLQVISACAMSFAHGANDVANAIGSFAAAYYVYETRTVPGSNSVVFPWILALGATGIVVGLATYGYNIMRVLGVKCVHITPSRGFAMELSTSLVIAVGSAYGLPLSTTHTITGATAGGGLAEGRARAISWWLYAKMFA
>Sce|comp17080_c0_seq1_1-972
MIWILLATYWELPVSTTHSIIGGIIGFALAFGGGKAVSWYEPRPDFPYVRGIVPIVISWFLSPLLAALITLVFFLLIRTFVLRRQNSTKIAFYVLPLLIFITIFISLLFVLTKGVSAVIKISTEKAAWISAVSGVGVALIGTVALWPLMKRMVAKYDREHTGSKDSGDVVIDAGGKFKDPEEDEFQKKVDRALSAKEVDPSDKSFGAYFTRFRNAALSGVTHDIHADIKEDKVQEMHDDAEKFDPRTEEVFKVLQVISACAMSFSHGANDVANAIGSFAAALMVYKTFKVPSSNSEVELWILALGGTGIVVGLATYGYNIMRVL
>Sce|comp171173_c0_seq1_1-375
HACLFTVQSTQGTFTDNRTKMAWTEYTWMIVIHGIVAWLDAYGIGANDVANSFGTSVGSKTLKLWSAVVIAAIFEFLGAMTLGGQVTRTIAGGIARPQTFAKFPALFMFGMLTAETAAMIWILLA
>Sce|comp20752_c0_seq1_1668-3362
HNRIFVHGLLCISQFVATQPIQYSRLVFVATDHTAHLSDHQNSSKRLESPTHGKMYEAITWMFAVGFVLALLVAYGLGANDVANMFGPSVGARALTMRQALLVAAIFEFLGAVLMGAGVADTIRSGITNIEFFTPRPDILAYGMMSALGGTGTWMIAATYWEFPVSSTQAIIASVAGMAIVAKGWNAVVWTARTPAFPYMKGMSFIALSWLVAPFLAGAASCFLFFVIRTFVLRAKNAYQRSLYVLPVFTFLTFFTVTWFTMVKGGVQYNWHKIPDVKKTWISIIIAAGTTALSIYPGLYLLKKNVNADLEAEEAAKASSDAVITVSADSKSVDDVDGAAPAPGLLGSIQRSRVWTALTYGMNYDIHKVIDTDERVAEIHANAEVFDRKAELTFKYLQVCTACANAFSHGSNEVANAVGPLAAIYQVWQTGAITSKAPVPTWLLAIGGLGICAGLATFGYTVMRAMGVKMTRLTNSRGFCVELCVAAVVIVASYCNLPMSSTLATVGAIAGVGVWEGRSGFNALLFVKMVSGWILTIIAAVSLTCLFMAQGLYAPSRGCPLPSF*
>Sel|comp12401_c1_seq1_114-1853
MVYAEVTWIFAVGVVLAVAVGYGLGANDLANMFGPSVGAKALTLKQAVLVAVVFEFVGAVLMGSGVTSTIRNGITDYRFFEDQPDILAFGMLCALLATGIWMLTATYWELPVSSTQAITAGVAAMAIVAEGFGSVKWWVPSNDFPYMKMSMGFIAISWIVAPLLAAIFSAVLYWVVRAVVLRSSNAYQRSLFLLPMFTCVTFFVVTFFIIEKGGPQYGWDKTPVAKKAWVSAVAAAGSTLIAGLVGIPLLRRKVERDVAEAAAAAKSADTAIDLPADKAAAADAAADEEAGAGAADGSLWGALQRSRAWRVATAGVNYDIHKIVDESERVREIHDAAEAFDSKAETSFKYLQVCTACANAFAHGSNEVANAVGPLAAIYQVWQEASVRSSSAVPHWLLAIGAFGICFGLATYGHYMIQAMGVKTARLTNSRGFVVELCVAAVVILASRLGLPMSSTPATVGAIAGVGLWEGRRGFNTRLFLKFCAGWVVTIIATVLLTMAFTAQGLYSPNKFSANERAIVGAYLNLTATQAAGALPASSAQAILSAAAGQKMPILSLLGPMETQAAALSAFDAAVWPRA*
>Sel|comp8589_c2_seq1_167-1975
MVLNAALWMVVVGGVVAWVMAYGIGANDVANAFATSVGSHTLKLKWAIVIAAIMETLGAILLGGSVSDTISGGVANPLAFKSTPDVFAYGMMCALTGAAIWLLVATYWELPVSTTHSIVGGVMGFALVYGGPSAVVWNKRISEFPFVSGVLAIVLSWFVSPVLAGLISSALFVVLRTFVLRSKNSAARAIWCLPILLAITIFVNLTFILLKGAKKVIKLPASTSLMICGICAVGGAIIGGAIGVPLLFRSKKRWDAVLADHEALPEESKDPLAAVNLSRSKEGSGLPNFLKTIEVDPEDKSLRAWCTRARNALTGGLNADVFACIGEDDGLHNIHASAEKFDPRVEQVFKYLQVISAAAVSFAHGANDVANAVGPFAAIYGIYQTGAISTKSAVEPWMLGGIGSTGIVIGLATWGWRIMRVLGVKMTAITPCRGFTMETTTALVTAFGSYLGIPLSTTQTHVGSTTGVGLSEGRRDAVKWGLLLKMFAGWVFTLFVGAIISGVLFAWGTYAPNISGAAEQNRLAASMAKGMTEMLGALNATGVKDAALAPVLAQLNATMNPTVGVFPSTATSATDLANLMDQTNTIFGRYVRLPAWISRTVG*
>Sel|comp8640_c0_seq1_537-2465
MAVPALPQYAWLVVMGAFGAFGFGWGTGANDVANAFGTSVGAKTLTLRQATVIAAIFEFAGALLLGRVVTNTIAGGIADPKVFARSPEIYAYGMVCALAVGAIWQAVASFAGYNVSSTHTIIGGILGFALVYRGSSAVQWATPDPASFPPYKGVVPIIMSWFFSPVLTAASSALIFSVLRSAVLRRNNAYNLAFYVLPIAVFITTFINVFFVFTKGAAKTLGADFTSHTSAWLSAAIAGGCCALTAFVVVPLLRRRAAHVHAKADADAAAAAEAAANGLKDPSATMIAVEEASDNPADQPWYKRALRGAKAAALYGTSVDIHKAVEEDEMIAAIHAHAEKFDPKTEMIFGYLQVFSAIAVIFAHGAGEVGFMAGPLSAIYDIYMNGRLSKAVQSQIWCVALSAASLVIGLATYGYNVTRAMGISLAKLSPSRGFAAELSTALVILVASQLGLPTSSSQCITGGIVGVGLLEGAAKGVNWRQFGKQFASWVATLFVVGLGVAAIFAQGIYSPSKVDGDAVMAYEKDVAGLTSNIAGGLNETLLGFESASRAGLLRNLSPMQWTELNSTVSELGTKAANVTSAGTVDGKKLISALKQALEIVQNNSILTLGQNEVFPDALICHGHIPANIRGDLPAACPHPLLT*
>Sel|comp8640_c0_seq2_537-2465
MAVPALPQYAWLVVMGAFGAFGFGWGTGANDVANAFGTSVGAKTLTLRQATVIAAIFEFAGALLLGRVVTNTIAGGIADPKVFARSPEIYAYGMVCALAVGAIWQAVASFAGYNVSSTHTIIGGILGFALVYRGSSAVQWATPDPASFPPYKGVVPIIMSWFFSPVLTAASSALIFSVLRSAVLRRNNAYNLAFYVLPIAVFITTFINVFFVFTKGAAKTLGADFTSHTSAWLSAAIAGGCCALTAFVVVPLLRRRAAHVHAKADADAAAAAEAAANGLKDPSATMIAVEEASDNPADQPWYKRALRGAKAAALYGTSVDIHKAVEEDEMIAAIHAHAEKFDPKTEMIFGYLQVFSAIAVIFAHGAGEVGFMAGPLSAIYDIYMNGRLSKAVQSQIWCVALSAASLVIGLATYGYNVTRAMGISLAKLSPSRGFAAELSTALVILVASQLGLPTSSSQCITGGIVGVGLLEGAAKGVNWRQFGKQFASWVATLFVVGLGVAAIFAQGIYSPSKVDGDAVMAYEKDVAGLTSNIAGGLNETLLGFESASRAGLLRNLSPMQWTELNSTVSELGTKAANVTSAGTVDGKKLISALKQALEIVQNNSILTLGQNEVFPDALICHGHIPANIRGDLPAACPHPLLT*
>Sel|comp8640_c0_seq3_537-2465
MAVPALPQYAWLVVMGAFGAFGFGWGTGANDVANAFGTSVGAKTLTLRQATVIAAIFEFAGALLLGRVVTNTIAGGIADPKVFARSPEIYAYGMVCALAVGAIWQAVASFAGYNVSSTHTIIGGILGFALVYRGSSAVQWATPDPASFPPYKGVVPIIMSWFFSPVLTAASSALIFSVLRSAVLRRNNAYNLAFYVLPIAVFITTFINVFFVFTKGAAKTLGADFTSHTSAWLSAAIAGGCCALTAFVVVPLLRRRAAHVHAKADADAAAAAEAAANGLKDPSATMIAVEEASDNPADQPWYKRALRGAKAAALYGTSVDIHKAVEEDEMIAAIHAHAEKFDPKTEMIFGYLQVFSAIAVIFAHGAGEVGFMAGPLSAIYDIYMNGRLSKAVQSQIWCVALSAASLVIGLATYGYNVTRAMGISLAKLSPSRGFAAELSTALVILVASQLGLPTSSSQCITGGIVGVGLLEGAAKGVNWRQFGKQFASWVATLFVVGLGVAAIFAQGIYSPSKVDGDAVMAYEKDVAGLTSNIAGGLNETLLGFESASRAGLLRNLSPMQWTELNSTVSELGTKAANVTSAGTVDGKKLISALKQALEIVQNNSILTLGQNEVFPDALICHGHIPANIRGDLPAACPHPLLT*
>Sta|comp53500_c0_seq2_3-944
AGQQIRPQRPKLPGELLTMAAAACSGETARCASAASSRRPKNSPPPFAASVSLNQLPPSAKRRPRALSQSSSHNASTSHAVSSRHNRQHPLSSPAQDRPSSFQVRASADSASTPPNDATFQSKEILESDTEGDAAVAQPALQGDTGNGAPSSSAGAGAPSGMAEAFDITPRTALTITALVTCSAFVLPFALKIATAGASVKIQGLTYLTLMLGFYMAWNIGANDVANAMGTSVGSGALTLRQAVLTAAILEFGGAFLVGSHVSQTMQSGIVNAQMFAGNPDLLFTGMLASLAAAGTWLQVASSYGWPVSTTHCI
>Sta|comp53500_c0_seq3_549-1199
GAVLVSATIDRQLGEYLGDFCEIPGRVVPRRVNPRGPTGTQLRIVYVVFGYLQVLSACFMSFAHGANDVANAIGPILAALSILQGPGAPALADSVATRVLVWGGFGIVAGLLVWGYKVIATIGKGITELTPTRGFAAEFSAATVVVVASRMGLPISATHTLVGAVMGVGLARGLNSVRFDVMKEIATSWIVTIPIGAVLSVLYTFILQRVLPSIAG*
>Sta|comp53500_c0_seq5_3-1781
AGQQIRPQRPKLPGELLTMAAAACSGETARCASAASSRRPKNSPPPFAASVSLNQLPPSAKRRPRALSQSSSHNASTSHAVSSRHNRQHPLSSPAQDRPSSFQVRASADSASTPPNDATFQSKEILESDTEGDAAVAQPALQGDTGNGAPSSSAGAGAPSGMAEAFDITPRTALTITALVTCSAFVLPFALKIATAGASVKIQGLTYLTLMLGFYMAWNIGANDVANAMGTSVGSGALTLRQAVLTAAILEFGGAFLVGSHVSQTMQSGIVNAQMFAGNPDLLFTGMLASLAAAGTWLQVASSYGWPVSTTHCIIGALVGFGLVNGGVEAVYWRSLARVVSSWIISPLFGGSIAYIVYRCIRMFVYDATNPGQAACQAAPVLVFLGVTAFSLSSLLGGGPVLWPVLQSLAAGTVGAVLVSATIDRQLGEYLGDFCEIPGRVVPRRVNPRGPTGTQLRIVYVVFGYLQVLSACFMSFAHGANDVANAIGPILAALSILQGPGAPALADSVATRVLVWGGFGIVAGLLVWGYKVIATIGKGITELTPTRGFAAEFSAATVVVVASRMGLPISATHTLVGAVMGVGLARGLNSVRF
>Sta|comp53500_c0_seq7_539-1189
GAVLVSATIDRQLGEYLGDFCEIPGRVVPRRVNPRGPTGTQLRIVYVVFGYLQVLSACFMSFAHGANDVANAIGPILAALSILQGPGAPALADSVATRVLVWGGFGIVAGLLVWGYKVIATIGKGITELTPTRGFAAEFSAATVVVVASRMGLPISATHTLVGAVMGVGLARGLNSVRFDVMKEIATSWIVTIPIGAVLSVLYTFILQRVLPSIAG*
>Sta|comp53500_c0_seq8_3-707
FIPERQGNRSGHSDQRNRASFRPWPPRLAAARPPAVHQQPRREDLKNRPKKRSASVFQRAAGSCDTGNGAPSSSAGAGAPSGMAEAFDITPRTALTITALVTCSAFVLPFALKIATAGASVKIQGLTYLTLMLGFYMAWNIGANDVANAMGTSVGSGALTLRQAVLTAAILEFGGAFLVGSHVSQTMQSGIVNAQMFAGNPDLLFTGMLASLAAAGTWLQVASSYGWPVSTTHCI
>Sta|comp53500_c0_seq9_3-1544
FIPERQGNRSGHSDQRNRASFRPWPPRLAAARPPAVHQQPRREDLKNRPKKRSASVFQRAAGSCDTGNGAPSSSAGAGAPSGMAEAFDITPRTALTITALVTCSAFVLPFALKIATAGASVKIQGLTYLTLMLGFYMAWNIGANDVANAMGTSVGSGALTLRQAVLTAAILEFGGAFLVGSHVSQTMQSGIVNAQMFAGNPDLLFTGMLASLAAAGTWLQVASSYGWPVSTTHCIIGALVGFGLVNGGVEAVYWRSLARVVSSWIISPLFGGSIAYIVYRCIRMFVYDATNPGQAACQAAPVLVFLGVTAFSLSSLLGGGPVLWPVLQSLAAGTVGAVLVSATIDRQLGEYLGDFCEIPGRVVPRRVNPRGPTGTQLRIVYVVFGYLQVLSACFMSFAHGANDVANAIGPILAALSILQGPGAPALADSVATRVLVWGGFGIVAGLLVWGYKVIATIGKGITELTPTRGFAAEFSAATVVVVASRMGLPISATHTLVGAVMGVGLARGLNSVRF
>Tet|comp15793_c0_seq1_3-776
VIGLATYGYNVTRAMGTMMANLSPSRGFAAELATALVVLVASQLALPTSSNQCITGGIVGVGLMEGALKGVNWKHFAKQFLSWVATLFVVGLGVAALFAQGVYSPSKIDGNQAILYEDRVSNLSSNMYKNFNSTLQDYEGAAQAGVLTQLPASKWAELNETVNTQAGIIKNLTAKAASSVVTPENNMNHLYRALDLYQQYSIFTLGQNKVFPGANVCNSGDAAEIAANSMIECPAPQFVPSWVELLPPYPEPVQGSP*
>Tet|comp22329_c0_seq1_2-886
PYTTGAWISAVVAAGVAAIACLFFPFLRRAAARVDAEGNPTDVEKVAPDGEYDEGTWQKKVADRLKPKHVDPEDKSMGAKLTRARNAMLVGVSTDIHEEIGRDAQTTAMHDAAEKFDPRTEQIFKYLQVLSACAVSFSHGANDVANAIGSFTAALATYQTGEVPGKEVNVAIWVLVLGATGIVVGLATYGYNIMKVLGVKCTHITPSRGFSMETATSFVVSVGSVFGLPLSTTHTICGATAGAGLVEGRLDAISWKVYGKMFCGWVVTLIFAAACSAAIFAYGIYTPSMQATPR*
>Tet|comp22329_c3_seq1_186-848
MALQGYLWILVLHAIVAWLDAYGIGANDVANAFGTSVGSKTLKIWMAVCIAAVFEFTGAVTLGGSVTKTVAGSIANTSTFEGSPAVFMYGMFCAETGAMVWILLATYLELPVSTTHSIIGGIMGFSLVFAGAKGVNWSKKTSEFPYTSGFVPVVLSWFISPIASAIVSGIIFFLIRTLVLRRKNSTKVAIWTLPVFLLITVFINLFFILTKGVKATVKIP
>Tet|comp25555_c5_seq1_117-1919
MEAGAPDILWLVVVGGIIAWVMAYGIGANDVANAFATSVGSRTLKLKWAIAIAVVMETTGAIFLGGSVSSTISGGVADPKTFANTPDIFAYGMLCALTAAAIWLLFATYAELPVSTTHSIVGGVIGFGLIYGGSKAIIWAGKTSSFPFYTGVVVIVASWFISPVLAGLMSYILYTILRLLVLRGPTAPNKSIWCLPILLFITVFVNLFFILYKGAKNIIKIDIVTAVWVSAAAGGGCALLGAAIGVPLLFRQKKTWESTIDEYRVAGKGVPGVLPTLRGKPEVVGKTALPKWMMVKDVDASDKSVAGYVQRFKNAAFGGLQQDIFEAVDNDSSLSDIHDNAERFDPVVEQVFKYLQIISAAAMSFAHGANDVANAVGPFAAIYGIYKYGYISSKSTVEMWMLAGIGATGIVVGLATYGWKIVRVLGVKLTAITPCRGFTMETTTALVTAFGSYLGIPLSTTQTHVGSTTGVGLAEGRKGAVKWSQLLKMFAGWVFTLIVGMVISGILFAWGTFAPNKTYGFQILDYQRAIAEATQANLAALNAANGVPPAELAALNSGFVDLSNSSSKHPWPSTTTPPGDVIPFLNDTTQMVLDNANLAF*
>Tet|comp25555_c5_seq2_346-2085
MAYGIGANDVANAFATSVGSRTLKLKWAIAIAVVMETTGAIFLGGSVSSTISGGVADPKTFANTPDIFAYGMLCALTAAAIWLLFATYAELPVSTTHSIVGGVIGFGLIYGGSKAIIWAGKTSSFPFYTGVVVIVASWFISPVLAGLMSYILYTILRLLVLRGPTAPNKSIWCLPILLFITVFVNLFFILYKGAKNIIKIDIVTAVWVSAAAGGGCALLGAAIGVPLLFRQKKTWESTIDEYRVAGKGVPGVLPTLRGKPEVVGKTALPKWMMVKDVDASDKSVAGYVQRFKNAAFGGLQQDIFEAVDNDSSLSDIHDNAERFDPVVEQVFKYLQIISAAAMSFAHGANDVANAVGPFAAIYGIYKYGYISSKSTVEMWMLAGIGATGIVVGLATYGWKIVRVLGVKLTAITPCRGFTMETTTALVTAFGSYLGIPLSTTQTHVGSTTGVGLAEGRKGAVKWSQLLKMFAGWVFTLIVGMVISGILFAWGTFAPNKTYGFQILDYQRAIAEATQANLAALNAANGVPPAELAALNSGFVDLSNSSSKHPWPSTTTPPGDVIPFLNDTTQMVLDNANLAF*
>Tet|comp25703_c10_seq1_166-1968
MVWETYTWIVVMGAVVAFFMAYGIGANDVANSFGTSVGSKALKLWHAVIIAGVCEFLGAMLLGAPTARTIAGSIAKNSAFERHPEVLMYGMLCALSAAAIWLLVATYLELAVSTTHSIVGAVMGFSLVFGGGSAIVWAERIDEFPYLRGVAVIAMSWIISPLACGFIVAIFFLTVRTIVLRPKNSTKRAFWLLPVLVFITVYINAFFVMFKGAAGKFKDLGENPAQCAWIAAVVAAGGTLFTLVVIMPFLHKKLQAWIEGSAGPSKCVFGDAGGVEAGDAKGVDASMDLESAKAGKPSFKDRFMKAATAGIKADIHDTAYEEDAHAVAVADNAEKFDASTEHVLSYLQVFTAMCDAFSHGANDVANSIGPFAAIWQVYTTQMATSRSTVPVWILAIGSLGIVVGLATYGYKIIRAIGVKLAHITPSRGFCVELGTAWIISLGSMFGLPLSTTHCQVGGTAGVGLVEGRKGVNWRLLLKTFGAWVMTLVVAGCFSAALFSAGAFAPSIPMARQIEQYEDGVLASSSEMLNVLNSTNLGNCTVPDAPTCNVGLNDTISSMGKDISDMLNPKNTQTLMPSDVLGVMNSSFGLYQEHSTIDTTP*
